// GENERATED by scripts/create-pack.ts --index: the handler map, by operationId, from the families' files (each
// handler named as its operation). Do not edit; add a handler to its family's file and generate again.
import type { Handler } from '@volter/world-core';
import * as account_owned_api_tokens from './account-owned-api-tokens.ts';
import * as accounts from './accounts.ts';
import * as custom_hostname_for_a_zone from './custom-hostname-for-a-zone.ts';
import * as dns_records_for_a_zone from './dns-records-for-a-zone.ts';
import * as domains from './domains.ts';
import * as durable_objects_namespace from './durable-objects-namespace.ts';
import * as notification_policies from './notification-policies.ts';
import * as notification_webhooks from './notification-webhooks.ts';
import * as r2_bucket from './r2-bucket.ts';
import * as turnstile from './turnstile.ts';
import * as user_api_tokens from './user-api-tokens.ts';
import * as worker_cron_trigger from './worker-cron-trigger.ts';
import * as worker_deployments from './worker-deployments.ts';
import * as worker_routes from './worker-routes.ts';
import * as worker_script from './worker-script.ts';
import * as worker_subdomain from './worker-subdomain.ts';
import * as worker_versions from './worker-versions.ts';
import * as workers from './workers.ts';
import * as zone from './zone.ts';

export const apiSemantics: Record<string, Handler> = {
  "account-api-tokens-list-tokens": account_owned_api_tokens.account_api_tokens_list_tokens,
  "accounts-list-accounts": accounts.accounts_list_accounts,
  "accounts-turnstile-widget-create": turnstile.accounts_turnstile_widget_create,
  "accounts-turnstile-widgets-list": turnstile.accounts_turnstile_widgets_list,
  "custom-hostname-for-a-zone-create-custom-hostname": custom_hostname_for_a_zone.custom_hostname_for_a_zone_create_custom_hostname,
  "custom-hostname-for-a-zone-edit-custom-hostname": custom_hostname_for_a_zone.custom_hostname_for_a_zone_edit_custom_hostname,
  "dns-records-for-a-zone-create-dns-record": dns_records_for_a_zone.dns_records_for_a_zone_create_dns_record,
  "durable-objects-namespace-list-namespaces": durable_objects_namespace.durable_objects_namespace_list_namespaces,
  getWorker: workers.getWorker,
  "notification-policies-create-a-notification-policy": notification_policies.notification_policies_create_a_notification_policy,
  "notification-policies-list-notification-policies": notification_policies.notification_policies_list_notification_policies,
  "notification-webhooks-create-a-webhook": notification_webhooks.notification_webhooks_create_a_webhook,
  "notification-webhooks-list-webhooks": notification_webhooks.notification_webhooks_list_webhooks,
  "r2-add-custom-domain": r2_bucket.r2_add_custom_domain,
  "r2-create-bucket": r2_bucket.r2_create_bucket,
  "r2-create-temp-access-credentials": r2_bucket.r2_create_temp_access_credentials,
  "r2-get-bucket": r2_bucket.r2_get_bucket,
  "r2-list-buckets": r2_bucket.r2_list_buckets,
  "r2-list-custom-domains": r2_bucket.r2_list_custom_domains,
  "user-api-tokens-verify-token": user_api_tokens.user_api_tokens_verify_token,
  "worker-assets-upload": worker_script.worker_assets_upload,
  "worker-cron-trigger-get-cron-triggers": worker_cron_trigger.worker_cron_trigger_get_cron_triggers,
  "worker-cron-trigger-update-cron-triggers": worker_cron_trigger.worker_cron_trigger_update_cron_triggers,
  "worker-deployments-create-deployment": worker_deployments.worker_deployments_create_deployment,
  "worker-deployments-list-deployments": worker_deployments.worker_deployments_list_deployments,
  "worker-domains-changeset": domains.worker_domains_changeset,
  "worker-domains-get-record": domains.worker_domains_get_record,
  "worker-domains-put-records": domains.worker_domains_put_records,
  "worker-list-script-secrets": worker_script.worker_list_script_secrets,
  "worker-put-script-secret": worker_script.worker_put_script_secret,
  "worker-routes-list-routes": worker_routes.worker_routes_list_routes,
  "worker-script-get-settings": worker_script.worker_script_get_settings,
  "worker-script-get-subdomain": worker_script.worker_script_get_subdomain,
  "worker-script-list-workers": worker_script.worker_script_list_workers,
  "worker-script-post-subdomain": worker_script.worker_script_post_subdomain,
  "worker-script-settings-get-settings": worker_script.worker_script_settings_get_settings,
  "worker-script-settings-patch-settings": worker_script.worker_script_settings_patch_settings,
  "worker-script-update-create-assets-upload-session": worker_script.worker_script_update_create_assets_upload_session,
  "worker-script-upload-worker-module": worker_script.worker_script_upload_worker_module,
  "worker-service-get": worker_script.worker_service_get,
  "worker-subdomain-create-subdomain": worker_subdomain.worker_subdomain_create_subdomain,
  "worker-subdomain-get-subdomain": worker_subdomain.worker_subdomain_get_subdomain,
  "worker-versions-get-version-detail": worker_versions.worker_versions_get_version_detail,
  "worker-versions-list-versions": worker_versions.worker_versions_list_versions,
  "worker-versions-upload-version": worker_versions.worker_versions_upload_version,
  "workers.domains.delete": domains.workers_domains_delete,
  "workers.domains.get": domains.workers_domains_get,
  "workers.domains.list": domains.workers_domains_list,
  "workers.domains.update": domains.workers_domains_update,
  "zones-get": zone.zones_get,
  "zones-post": zone.zones_post,
};
