// GENERATED by scripts/create-pack.ts --index: the handler map, by operationId, from the families' files (each
// handler named as its operation). Do not edit; add a handler to its family's file and generate again.
import type { Handler } from '@volter/world-core';
import * as client from './client.ts';
import * as dev_browser from './dev_browser.ts';
import * as environment from './environment.ts';
import * as me from './me.ts';
import * as oauth from './oauth.ts';
import * as oauth_callback from './oauth_callback.ts';
import * as tickets from './tickets.ts';
import * as well_known from './well-known.ts';

export const fapiSemantics: Record<string, Handler> = {
  acceptTicket: tickets.acceptTicket,
  attemptSignInFactorOne: client.attemptSignInFactorOne,
  attemptSignUpsVerification: client.attemptSignUpsVerification,
  createDevBrowser: dev_browser.createDevBrowser,
  createSessionToken: client.createSessionToken,
  createSessionTokenWithTemplate: client.createSessionTokenWithTemplate,
  createSignIn: client.createSignIn,
  createSignUps: client.createSignUps,
  getClient: client.getClient,
  getEnvironment: environment.getEnvironment,
  getJWKS: well_known.getJWKS,
  getOAuthToken: oauth.getOAuthToken,
  getOauthCallback: oauth_callback.getOauthCallback,
  getSession: client.getSession,
  getSignIn: client.getSignIn,
  getSignUps: client.getSignUps,
  handshakeClient: client.handshakeClient,
  postClient: client.postClient,
  prepareSignInFactorOne: client.prepareSignInFactorOne,
  prepareSignUpsVerification: client.prepareSignUpsVerification,
  putClient: client.putClient,
  removeClientSessionsAndRetainCookie: client.removeClientSessionsAndRetainCookie,
  requestOAuthAuthorize: oauth.requestOAuthAuthorize,
  submitOAuthConsent: me.submitOAuthConsent,
  touchSession: client.touchSession,
  updateEnvironment: environment.updateEnvironment,
  updateSignUps: client.updateSignUps,
};
