// GENERATED by scripts/create-pack.ts (--init, --index): a fixed file. The kernel serves the discovery door, the clock,
// the World's doors, the vendor's screens and the API from the pack's parts (architecture, "The pack contract").
import { createPackFetch, type DerivedFetch, type DerivedSurface, type PackFetchOptions } from '@volter/world-core';
import surface from './generated/surface.gen.json' with { type: 'json' };
import { manifest } from './manifest.ts';
import * as doors from './semantics/doors.ts';
import { apiSemantics } from './semantics/index.ts';
import { screen as screen_qstash } from './screens/qstash.tsx';
import { screen as screen_redis } from './screens/redis.tsx';
import { screen as screen_sign_in } from './screens/sign-in.tsx';

export function createApiLaneFetch(options: PackFetchOptions = {}): DerivedFetch {
  return createPackFetch({
    manifest,
    surface: surface as DerivedSurface,
    handlers: apiSemantics,
    doors,
    screens: { "qstash": screen_qstash, "redis": screen_redis, "sign-in": screen_sign_in },
  }, options);
}
