// GENERATED by scripts/create-pack.ts --index: the handler map, by operationId, from the families' files (each
// handler named as its operation). Do not edit; add a handler to its family's file and generate again.
import type { Handler } from '@volter/world-core';
import * as oauth from './oauth.ts';

export const linearSemantics: Record<string, Handler> = {
  oauthToken: oauth.oauthToken,
};
