// GENERATED by scripts/create-pack.ts --index: the handler map, by operationId, from the families' files (each
// handler named as its operation). Do not edit; add a handler to its family's file and generate again.
import type { Handler } from '@volter/world-core';
import * as messages from './messages.ts';
import * as models from './models.ts';

export const anthropicSemantics: Record<string, Handler> = {
  beta_messages_count_tokens_post: messages.beta_messages_count_tokens_post,
  beta_messages_post: messages.beta_messages_post,
  messages_post: messages.messages_post,
  models_list: models.models_list,
};
