// GENERATED by scripts/create-pack.ts (--init, --index): a fixed file. The kernel serves the discovery door, the clock,
// the World's doors, the vendor's screens and the API from the pack's parts (architecture, "The pack contract").
import { createPackFetch, type DerivedFetch, type DerivedSurface, type PackFetchOptions } from '@volter/world-core';
import surface from './generated/surface.gen.json' with { type: 'json' };
import { manifest } from './manifest.ts';
import { around } from './semantics/around.ts';
import { board } from './semantics/board.ts';
import { graphql } from './semantics/graphql.ts';
import schema from './generated/graphql-sdl.gen.json' with { type: 'json' };
import graphqlSurface from './generated/graphql.gen.json' with { type: 'json' };
import * as doors from './semantics/doors.ts';
import { githubSemantics } from './semantics/index.ts';
import { screen as screen_apps } from './screens/apps.tsx';
import { screen as screen_device } from './screens/device.tsx';
import { screen as screen_git } from './screens/git.ts';
import { screen as screen_login } from './screens/login.tsx';
import { screen as screen_oauth } from './screens/oauth.tsx';
import { screen as screen_oidc } from './screens/oidc.ts';
import { screen as screen_organizations } from './screens/organizations.tsx';
import { screen as screen_raw } from './screens/raw.ts';
import { screen as screen_repo } from './screens/repo.tsx';
import { screen as screen_session } from './screens/session.ts';
import { screen as screen_sessions } from './screens/sessions.tsx';
import { screen as screen_settings } from './screens/settings.tsx';

export function createGithubFetch(options: PackFetchOptions = {}): DerivedFetch {
  return createPackFetch({
    manifest,
    surface: surface as DerivedSurface,
    handlers: githubSemantics,
    doors,
    around,
    board,
    graphql: { ...graphql, operations: graphqlSurface.operations as NonNullable<typeof graphql.operations>, sdl: schema.sdl },
    screens: { "apps": screen_apps, "device": screen_device, "git": screen_git, "login": screen_login, "oauth": screen_oauth, "oidc": screen_oidc, "organizations": screen_organizations, "raw": screen_raw, "repo": screen_repo, "session": screen_session, "sessions": screen_sessions, "settings": screen_settings },
  }, options);
}
