// GENERATED by scripts/create-pack.ts --index: the handler map, by operationId, from the families' files (each
// handler named as its operation). Do not edit; add a handler to its family's file and generate again.
import type { Handler } from '@volter/world-core';
import * as apps from './apps.ts';
import * as auth from './auth.ts';
import * as chat from './chat.ts';
import * as conversations from './conversations.ts';
import * as dnd from './dnd.ts';
import * as emoji from './emoji.ts';
import * as files from './files.ts';
import * as oauth from './oauth.ts';
import * as pins from './pins.ts';
import * as reactions from './reactions.ts';
import * as team from './team.ts';
import * as tooling from './tooling.ts';
import * as usergroups from './usergroups.ts';
import * as users from './users.ts';
import * as views from './views.ts';

export const slackSemantics: Record<string, Handler> = {
  apps_connections_open: apps.apps_connections_open,
  apps_manifest_create: apps.apps_manifest_create,
  apps_manifest_delete: apps.apps_manifest_delete,
  apps_manifest_export: apps.apps_manifest_export,
  apps_manifest_update: apps.apps_manifest_update,
  apps_manifest_validate: apps.apps_manifest_validate,
  apps_uninstall: apps.apps_uninstall,
  auth_revoke: auth.auth_revoke,
  auth_test: auth.auth_test,
  chat_delete: chat.chat_delete,
  chat_deleteScheduledMessage: chat.chat_deleteScheduledMessage,
  chat_getPermalink: chat.chat_getPermalink,
  chat_meMessage: chat.chat_meMessage,
  chat_postEphemeral: chat.chat_postEphemeral,
  chat_postMessage: chat.chat_postMessage,
  chat_scheduleMessage: chat.chat_scheduleMessage,
  chat_scheduledMessages_list: chat.chat_scheduledMessages_list,
  chat_unfurl: chat.chat_unfurl,
  chat_update: chat.chat_update,
  conversations_archive: conversations.conversations_archive,
  conversations_create: conversations.conversations_create,
  conversations_history: conversations.conversations_history,
  conversations_info: conversations.conversations_info,
  conversations_invite: conversations.conversations_invite,
  conversations_inviteShared: conversations.conversations_inviteShared,
  conversations_join: conversations.conversations_join,
  conversations_leave: conversations.conversations_leave,
  conversations_list: conversations.conversations_list,
  conversations_listConnectInvites: conversations.conversations_listConnectInvites,
  conversations_mark: conversations.conversations_mark,
  conversations_members: conversations.conversations_members,
  conversations_open: conversations.conversations_open,
  conversations_rename: conversations.conversations_rename,
  conversations_replies: conversations.conversations_replies,
  conversations_setPurpose: conversations.conversations_setPurpose,
  conversations_setTopic: conversations.conversations_setTopic,
  conversations_unarchive: conversations.conversations_unarchive,
  dnd_endSnooze: dnd.dnd_endSnooze,
  dnd_setSnooze: dnd.dnd_setSnooze,
  emoji_list: emoji.emoji_list,
  files_completeUploadExternal: files.files_completeUploadExternal,
  files_delete: files.files_delete,
  files_getUploadURLExternal: files.files_getUploadURLExternal,
  files_list: files.files_list,
  oauth_v2_access: oauth.oauth_v2_access,
  pins_add: pins.pins_add,
  pins_list: pins.pins_list,
  pins_remove: pins.pins_remove,
  reactions_add: reactions.reactions_add,
  reactions_get: reactions.reactions_get,
  reactions_remove: reactions.reactions_remove,
  team_info: team.team_info,
  tooling_tokens_rotate: tooling.tooling_tokens_rotate,
  usergroups_create: usergroups.usergroups_create,
  usergroups_disable: usergroups.usergroups_disable,
  usergroups_enable: usergroups.usergroups_enable,
  usergroups_list: usergroups.usergroups_list,
  usergroups_update: usergroups.usergroups_update,
  usergroups_users_list: usergroups.usergroups_users_list,
  usergroups_users_update: usergroups.usergroups_users_update,
  users_conversations: users.users_conversations,
  users_getPresence: users.users_getPresence,
  users_info: users.users_info,
  users_list: users.users_list,
  users_profile_get: users.users_profile_get,
  users_profile_set: users.users_profile_set,
  users_setPresence: users.users_setPresence,
  views_publish: views.views_publish,
};
