// GENERATED by scripts/create-pack.ts (--init, --index): a fixed file. The kernel serves the discovery door, the clock,
// the World's doors, the vendor's screens and the API from the pack's parts (architecture, "The pack contract").
import { createPackFetch, type DerivedFetch, type DerivedSurface, type PackFetchOptions } from '@volter/world-core';
import surface from './generated/surface.gen.json' with { type: 'json' };
import { manifest } from './manifest.ts';
import { around } from './semantics/around.ts';
import { clock } from './semantics/clock.ts';
import * as doors from './semantics/doors.ts';
import { stripeSemantics } from './semantics/index.ts';
import { screen as screen_billing_portal } from './screens/billing-portal.tsx';
import { screen as screen_checkout_js } from './screens/checkout-js.ts';
import { screen as screen_checkout } from './screens/checkout.tsx';
import { screen as screen_connect_onboarding } from './screens/connect-onboarding.tsx';
import { screen as screen_dashboard } from './screens/dashboard.tsx';
import { screen as screen_stripe_js } from './screens/stripe-js.ts';

export function createStripeFetch(options: PackFetchOptions = {}): DerivedFetch {
  return createPackFetch({
    manifest,
    surface: surface as DerivedSurface,
    handlers: stripeSemantics,
    doors,
    around,
    clock,
    screens: { "billing-portal": screen_billing_portal, "checkout-js": screen_checkout_js, "checkout": screen_checkout, "connect-onboarding": screen_connect_onboarding, "dashboard": screen_dashboard, "stripe-js": screen_stripe_js },
  }, options);
}
