// Stripe's manifest: the vendor facts its published spec does not carry, and the resources the
// derived core serves (docs/contributing/architecture.md, "Protocol 3"). The surface itself is
// generated (./generated/surface.gen.json, from ../spec by scripts/derive-pack.ts).
import type { DerivedManifest } from '@volter/world-core';
import { data, values } from './semantics/events.ts';
import { STRIPE_EVENTS } from './semantics/shared.ts';
import { states } from './semantics/states.ts';

export const manifest: DerivedManifest = {
  vendor: 'stripe',
  service: 'stripe',
  body: { form: { coerce: true } },
  ids: { template: '{prefix}_twin_{n}', acceptProvided: true },
  unmodeled: [
    'DeleteAccountsAccountBankAccountsId',
    'DeleteAccountsAccountExternalAccountsId',
    'DeleteAccountsAccountPeoplePerson',
    'DeleteAccountsAccountPersonsPerson',
    'DeleteCouponsCoupon',
    'DeleteCustomersCustomerSourcesId',
    'DeleteCustomersCustomerSubscriptionsSubscriptionExposedId',
    'DeleteCustomersCustomerTaxIdsId',
    'DeleteEphemeralKeysKey',
    'DeleteInvoiceitemsInvoiceitem',
    'DeleteInvoicesInvoice',
    'DeleteProductsId',
    'DeleteProductsProductFeaturesId',
    'DeleteRadarValueListItemsItem',
    'DeleteRadarValueListsValueList',
    'DeleteSubscriptionItemsItem',
    'DeleteTaxIdsId',
    'DeleteTerminalConfigurationsConfiguration',
    'DeleteTerminalLocationsLocation',
    'DeleteTerminalReadersReader',
    'DeleteTestHelpersTestClocksTestClock',
    'DeleteWebhookEndpointsWebhookEndpoint',
    'GetAccountsAccountBankAccountsId',
    'GetAccountsAccountCapabilities',
    'GetAccountsAccountCapabilitiesCapability',
    'GetAccountsAccountExternalAccountsId',
    'GetAccountsAccountPeople',
    'GetAccountsAccountPeoplePerson',
    'GetAccountsAccountPersonsPerson',
    'GetApplicationFeesFeeRefundsId',
    'GetApplicationFeesId',
    'GetAppsSecrets',
    'GetBalanceHistory',
    'GetBalanceHistoryId',
    'GetBalanceTransactionsId',
    'GetBillingAlertsId',
    'GetBillingCreditGrantsId',
    'GetBillingMetersId',
    'GetBillingPortalConfigurationsConfiguration',
    'GetChargesChargeDispute',
    'GetChargesChargeRefunds',
    'GetChargesChargeRefundsRefund',
    'GetClimateOrdersOrder',
    'GetCreditNotesId',
    'GetCreditNotesPreview',
    'GetCustomersCustomerBalanceTransactionsTransaction',
    'GetCustomersCustomerCashBalanceTransactionsTransaction',
    'GetCustomersCustomerPaymentMethods',
    'GetCustomersCustomerPaymentMethodsPaymentMethod',
    'GetCustomersCustomerSourcesId',
    'GetCustomersCustomerSubscriptions',
    'GetCustomersCustomerSubscriptionsSubscriptionExposedId',
    'GetCustomersCustomerTaxIds',
    'GetCustomersCustomerTaxIdsId',
    'GetDisputesDispute',
    'GetEntitlementsActiveEntitlements',
    'GetEntitlementsFeaturesId',
    'GetEventsId',
    'GetFileLinksLink',
    'GetFilesFile',
    'GetFinancialConnectionsAccountsAccount',
    'GetFinancialConnectionsSessionsSession',
    'GetFinancialConnectionsTransactions',
    'GetFinancialConnectionsTransactionsTransaction',
    'GetIdentityVerificationReportsReport',
    'GetIdentityVerificationSessionsSession',
    'GetInvoiceitemsInvoiceitem',
    'GetInvoicesInvoiceLines',
    'GetIssuingAuthorizationsAuthorization',
    'GetIssuingCardholdersCardholder',
    'GetIssuingDisputesDispute',
    'GetIssuingPersonalizationDesignsPersonalizationDesign',
    'GetIssuingTransactionsTransaction',
    'GetLinkAccountSessionsSession',
    'GetLinkedAccounts',
    'GetLinkedAccountsAccount',
    'GetMandatesMandate',
    'GetPaymentIntentsIntent',
    'GetPaymentIntentsSearch',
    'GetPaymentLinksPaymentLink',
    'GetPayoutsPayout',
    'GetProductsId',
    'GetProductsProductFeaturesId',
    'GetProductsSearch',
    'GetQuotesQuote',
    'GetRadarValueListItems',
    'GetRadarValueListItemsItem',
    'GetRadarValueListsValueList',
    'GetRefundsRefund',
    'GetReportingReportRunsReportRun',
    'GetReviewsReview',
    'GetSetupIntentsIntent',
    'GetSourcesSource',
    'GetSubscriptionItems',
    'GetSubscriptionItemsItem',
    'GetSubscriptionSchedulesSchedule',
    'GetSubscriptionsSearch',
    'GetTaxCalculationsCalculation',
    'GetTaxIdsId',
    'GetTaxRatesTaxRate',
    'GetTaxRegistrationsId',
    'GetTaxTransactionsTransaction',
    'GetTerminalConfigurationsConfiguration',
    'GetTerminalLocationsLocation',
    'GetTerminalReadersReader',
    'GetTestHelpersTestClocks',
    'GetTestHelpersTestClocksTestClock',
    'GetTokensToken',
    'GetTopups',
    'GetTopupsTopup',
    'GetTransfersTransfer',
    'GetTransfersTransferReversalsId',
    'GetTreasuryFinancialAccountsFinancialAccount',
    'GetTreasuryInboundTransfers',
    'GetTreasuryInboundTransfersId',
    'GetTreasuryOutboundPayments',
    'GetTreasuryOutboundPaymentsId',
    'GetTreasuryOutboundTransfers',
    'GetTreasuryOutboundTransfersOutboundTransfer',
    'GetTreasuryReceivedCredits',
    'GetTreasuryReceivedCreditsId',
    'GetTreasuryReceivedDebits',
    'GetTreasuryReceivedDebitsId',
    'GetTreasuryTransactionEntries',
    'GetTreasuryTransactionEntriesId',
    'GetTreasuryTransactions',
    'GetTreasuryTransactionsId',
    'GetWebhookEndpointsWebhookEndpoint',
    'PostAccountsAccount',
    'PostAccountsAccountBankAccounts',
    'PostAccountsAccountBankAccountsId',
    'PostAccountsAccountCapabilitiesCapability',
    'PostAccountsAccountExternalAccounts',
    'PostAccountsAccountExternalAccountsId',
    'PostAccountsAccountPeople',
    'PostAccountsAccountPeoplePerson',
    'PostAccountsAccountPersons',
    'PostAccountsAccountPersonsPerson',
    'PostApplicationFeesFeeRefundsId',
    'PostApplicationFeesIdRefunds',
    'PostBillingAlerts',
    'PostBillingAlertsIdActivate',
    'PostBillingAlertsIdArchive',
    'PostBillingAlertsIdDeactivate',
    'PostBillingCreditGrants',
    'PostBillingCreditGrantsId',
    'PostBillingMeters',
    'PostBillingMetersId',
    'PostBillingMetersIdDeactivate',
    'PostBillingMetersIdReactivate',
    'PostBillingPortalConfigurationsConfiguration',
    'PostCharges',
    'PostChargesCharge',
    'PostChargesChargeCapture',
    'PostChargesChargeRefunds',
    'PostChargesChargeRefundsRefund',
    'PostCheckoutSessionsSession',
    'PostCheckoutSessionsSessionExpire',
    'PostClimateOrders',
    'PostClimateOrdersOrder',
    'PostClimateOrdersOrderCancel',
    'PostCouponsCoupon',
    'PostCreditNotes',
    'PostCreditNotesId',
    'PostCreditNotesIdVoid',
    'PostCustomersCustomerBalanceTransactions',
    'PostCustomersCustomerBalanceTransactionsTransaction',
    'PostCustomersCustomerSources',
    'PostCustomersCustomerSubscriptions',
    'PostCustomersCustomerSubscriptionsSubscriptionExposedId',
    'PostCustomersCustomerTaxIds',
    'PostDisputesDispute',
    'PostDisputesDisputeClose',
    'PostEntitlementsFeatures',
    'PostEntitlementsFeaturesId',
    'PostFileLinks',
    'PostFileLinksLink',
    'PostFiles',
    'PostFinancialConnectionsAccountsAccountDisconnect',
    'PostFinancialConnectionsSessions',
    'PostIdentityVerificationSessions',
    'PostIdentityVerificationSessionsSession',
    'PostInvoiceitems',
    'PostInvoiceitemsInvoiceitem',
    'PostInvoicesInvoice',
    'PostInvoicesInvoiceFinalize',
    'PostInvoicesInvoiceMarkUncollectible',
    'PostInvoicesInvoiceSend',
    'PostIssuingAuthorizationsAuthorization',
    'PostIssuingCardholdersCardholder',
    'PostIssuingDisputes',
    'PostIssuingDisputesDispute',
    'PostIssuingDisputesDisputeSubmit',
    'PostIssuingPersonalizationDesigns',
    'PostIssuingPersonalizationDesignsPersonalizationDesign',
    'PostIssuingTransactionsTransaction',
    'PostLinkAccountSessions',
    'PostPaymentIntentsIntent',
    'PostPaymentIntentsIntentApplyCustomerBalance',
    'PostPaymentIntentsIntentCapture',
    'PostPaymentIntentsIntentConfirm',
    'PostPaymentIntentsIntentIncrementAuthorization',
    'PostPaymentIntentsIntentVerifyMicrodeposits',
    'PostPaymentLinks',
    'PostPaymentLinksPaymentLink',
    'PostPaymentMethods',
    'PostPaymentMethodsPaymentMethod',
    'PostPaymentMethodsPaymentMethodAttach',
    'PostPayoutsPayout',
    'PostPayoutsPayoutCancel',
    'PostPlans',
    'PostPricesPrice',
    'PostProductsId',
    'PostProductsProductFeatures',
    'PostQuotes',
    'PostQuotesQuote',
    'PostQuotesQuoteAccept',
    'PostQuotesQuoteCancel',
    'PostQuotesQuoteFinalize',
    'PostRadarValueLists',
    'PostRadarValueListsValueList',
    'PostRefundsRefund',
    'PostRefundsRefundCancel',
    'PostReportingReportRuns',
    'PostReviewsReviewApprove',
    'PostSetupIntents',
    'PostSetupIntentsIntent',
    'PostSetupIntentsIntentCancel',
    'PostSetupIntentsIntentConfirm',
    'PostSetupIntentsIntentVerifyMicrodeposits',
    'PostSources',
    'PostSourcesSource',
    'PostSubscriptionItems',
    'PostSubscriptionItemsItem',
    'PostSubscriptionSchedules',
    'PostSubscriptionSchedulesSchedule',
    'PostSubscriptionSchedulesScheduleCancel',
    'PostSubscriptionSchedulesScheduleRelease',
    'PostSubscriptions',
    'PostTaxCalculations',
    'PostTaxIds',
    'PostTaxRates',
    'PostTaxRatesTaxRate',
    'PostTaxRegistrations',
    'PostTaxRegistrationsId',
    'PostTerminalConfigurations',
    'PostTerminalConfigurationsConfiguration',
    'PostTerminalLocations',
    'PostTerminalLocationsLocation',
    'PostTerminalReaders',
    'PostTerminalReadersReader',
    'PostTestHelpersIssuingPersonalizationDesignsPersonalizationDesignActivate',
    'PostTestHelpersIssuingPersonalizationDesignsPersonalizationDesignDeactivate',
    'PostTestHelpersIssuingPersonalizationDesignsPersonalizationDesignReject',
    'PostTestHelpersTestClocks',
    'PostTestHelpersTestClocksTestClockAdvance',
    'PostTestHelpersTreasuryInboundTransfersIdSucceed',
    'PostTokens',
    'PostTopups',
    'PostTopupsTopup',
    'PostTopupsTopupCancel',
    'PostTransfersIdReversals',
    'PostTransfersTransfer',
    'PostTransfersTransferReversalsId',
    'PostTreasuryFinancialAccounts',
    'PostTreasuryFinancialAccountsFinancialAccount',
    'PostTreasuryInboundTransfers',
    'PostTreasuryInboundTransfersInboundTransferCancel',
    'PostTreasuryOutboundPayments',
    'PostTreasuryOutboundPaymentsIdCancel',
    'PostTreasuryOutboundTransfers',
    'PostTreasuryOutboundTransfersOutboundTransferCancel',
    'PostWebhookEndpointsWebhookEndpoint',
  ],
  time: 'unix',
  error: { error: { type: '{kind}', message: '{message}', code: '{code}', param: '{param}' } },
  errorOmitsAbsent: true,
  defaultKind: 'invalid_request_error',
  readOnly: { status: 405, kind: 'invalid_request_error', message: 'twin is read-only; omit readOnly to accept writes' },
  version: {
    header: 'stripe-version',
    pattern: '^\\d{4}-\\d{2}-\\d{2}(\\.[a-z_]+)?$',
    error: { status: 400, kind: 'invalid_request_error', code: 'invalid_api_version', message: 'Invalid Stripe version: {value}. Check the API version reference: https://stripe.com/docs/api/versioning' },
  },
  // source: https://github.com/stripe/stripe-mock/issues/31 "Unrecognized request URL (GET: /v1/test)."
  // source: spec:/components/schemas/api_errors/properties/type "invalid_request_error"
  // Stripe's published API answer, shown by its maintainer for an unknown URL.
  gap: { status: 404, kind: 'invalid_request_error', message: 'Unrecognized request URL ({method}: {path}). Please see https://stripe.com/docs or we can help at https://support.stripe.com/.' },
  notFound: { status: 404, kind: 'invalid_request_error', code: 'resource_missing', message: "No such {object}: '{id}'" },
  list: {
    style: 'envelope',
    envelope: { object: 'list', url: '{url}', has_more: '{has_more}', data: '{data}' },
    limit: { param: 'limit', default: 10, max: 100 },
    after: 'starting_after',
    before: 'ending_before',
  },
  deleted: { id: '{id}', object: '{object}', deleted: true },
  expandParam: 'expand',
  idempotency: {
    header: 'idempotency-key',
    storedAs: '_idempotency',
    conflict: {
      status: 400,
      kind: 'idempotency_error',
      message: 'Keys for idempotent requests can only be used with the same parameters they were originally used with. Provide a new idempotency key, or use the original parameters that were used with this key.',
    },
  },
  // the pack as the World registers it (world-core packRegistry)
  // the fail-closed ceiling on live calls against Stripe (world-core rateBudget.ts, architecture D8), inside its sandbox
  // allowance
  // source: https://docs.stripe.com/rate-limits "25 requests per second"
  rateBudget: {
    // the vendor's documented allowance this budget stays inside (cited above)
    allowance: { perMinute: 1500, source: 'https://docs.stripe.com/rate-limits' },
    windowMs: 60_000,
    ceiling: 120,
    defaultWeight: 1,
    maxRetryAfterSeconds: 300,
    rules: [
      { match: '^POST /v1/payouts$', weight: 5 },
      { match: '^(POST|DELETE) ', weight: 2 },
    ],
    reason:
      'Stripe documents scalar limits (docs.stripe.com/rate-limits, read 2026-07-26): 100 requests/second in live mode, 25/second in ' +
      'sandbox, 25/second for an individual endpoint unless noted, 15 payout creates/second; over it, 429 with a Stripe-Rate-Limited-Reason ' +
      'header. 120 weighted units / 60s is 2 requests/second, 2% of live mode and 8% of the tightest general limit. POST/DELETE cost 2, a ' +
      'judgement about blast radius (a write creates a charge, refund or receipt e-mail and cannot be taken back), not a published ratio; ' +
      "POST /v1/payouts costs 5 because payout creation is documented at 15/second. Stripe's own window is a second, so an intra-second " +
      'burst reaches its limiter first; the 429 cooldown is the backstop for that shape.',
  },
  descriptor: {
    protocol: '3',
    transport: 'rest',
    archetype: 'crud',
    bin: 'world-stripe',
    resources: ['charge', 'customer', 'payment_intent', 'setup_intent', 'payment_method', 'subscription', 'price', 'product', 'invoice', 'invoiceitem', 'refund', 'event'],
    specSource: "Stripe's OpenAPI document (spec/, provenance in spec/SOURCE.md)",
    description: 'Stripe REST twin — spec-correct shapes, signed events, and the hosted pages an application sends people through.',
    // Stripe.js calls the same-origin '/v1/…' and loads from api.stripe.com — the dev proxy forwards '/v1/' to the twin
    // and strips the absolute host so calls come back same-origin
    browserRouting: { apiPathPrefix: '/v1/', loaderHost: 'https://api.stripe.com' },
    // the official server SDK and its Python bindings, and the STRIPE_* credential stems (NEXT_PRIVATE_STRIPE_* too);
    // `stripeconnect` is deliberately not claimed: no Connect-only credential stem is modelled
    adoption: { pypi: ['stripe'], sdks: ['stripe'], envStems: ['STRIPE', 'NEXTPRIVATESTRIPE'] },
    // the API and the screens' hosts, each claimed for the paths its screens serve: an application that sends a person
    // to one of their urls lands in the World; any other path on a claimed host is refused in a World rather than sent
    // to the real Stripe
    // a World's applications hold the platform's keys the dashboard shows (the credential door), never fixtures: the API
    // refuses a key Stripe did not issue
    credentialDoor: { path: '/_twin/app-credentials', body: {}, fill: { STRIPE_SECRET_KEY: 'secret_key', STRIPE_API_KEY: 'secret_key', STRIPE_PRIVATE_KEY: 'secret_key', BILLING_STRIPE_API_KEY: 'secret_key', STRIPE_PUBLISHABLE_KEY: 'publishable_key', NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: 'publishable_key', NEXT_PUBLIC_STRIPE_PUBLIC_KEY: 'publishable_key', NEXT_PUBLIC_STRIPE_KEY: 'publishable_key', STRIPE_WEBHOOK_SECRET: 'webhook_secret', STRIPE_WEBHOOK_SIGNING_SECRET: 'webhook_secret', STRIPE_ENDPOINT_SECRET: 'webhook_secret', STRIPE_WEBHOOK_SECRET_KEY: 'webhook_secret', NEXT_PRIVATE_STRIPE_WEBHOOK_SECRET: 'webhook_secret', BILLING_STRIPE_WEBHOOK_SECRET: 'webhook_secret', STRIPE_CONNECT_WEBHOOK_SECRET: 'connect_webhook_secret', STRIPE_WEBHOOK_SECRET_CONNECT: 'connect_webhook_secret', STRIPE_CONNECT_WEBHOOK_SIGNING_SECRET: 'connect_webhook_secret' } },
    hosts: [
      { host: 'api.stripe.com' }, { host: 'checkout.stripe.com', pathPattern: '^/c/pay/' }, { host: 'billing.stripe.com', pathPattern: '^/p/session/' },
      { host: 'connect.stripe.com', pathPattern: '^/setup/' },
      { host: 'dashboard.stripe.com', pathPattern: '^/customers(?:/[^/]+)?/?$|^/radar/lists(?:/[^/]+)?/?$|^/test/issuing/balance/?$|^/settings/public/?$' },
      { host: 'verify.stripe.com', pathPattern: '^/start/' },
      { host: 'js.stripe.com', pathPattern: '^/v3/?$|^/(v3|[a-z]+)/stripe\\.js$' },
    ],
  },
  // what GET /twin says this twin is
  discovery: {
    twinOf: 'the Stripe REST API, Checkout, the customer portal, Connect onboarding, and Stripe.js',
    stores: 'customers, payment objects, checkout sessions, products and prices, subscriptions and invoices, Connect accounts, Issuing, and signed events',
  },
  // the World's doors (./semantics/doors.ts): what stands in for an act Stripe's API does not have
  doors: [
    { id: 'account', method: 'POST', path: '/_twin/account', note: "the platform's own account settings, as the Dashboard changes them" },
    { id: 'appCredentials', method: 'POST', path: '/_twin/app-credentials', note: 'the platform\'s API keys (secret and publishable), as the runtime issues them' },
    { id: 'webhookEndpoints', method: 'POST', path: '/_twin/webhook-endpoints', note: '{ url, events, connect? }: an endpoint added on the Dashboard\'s Webhooks page, signed with the secret the World\'s application holds' },
    { id: 'drain', method: 'POST', path: '/_twin/drain', note: "time's events, sent when a runner drives them: payouts paid and funds made available" },
  ],
  // The screens applications and people reach (docs/contributing/architecture.md, "Screens"). Demand is the
  // applications' code that sends a customer to the page (journeys/demand.json).
  screens: [
    { id: 'checkout-js', kind: 'content', host: 'api.stripe.com', path: '/v1/payment_pages/{session}', takes: ['POST'], status: 'done', source: 'https://docs.stripe.com/payments/advanced', demand: 'Postiz CheckoutProvider: the published Stripe.js contract over the session store; the private wire is authored (screens/checkout-js.ts).' },
    {
      id: 'checkout', kind: 'flow', host: 'checkout.stripe.com', path: '/c/pay/{session}', status: 'done',
      demand: 'Dub, Rallly, Postiz and Twenty send customers to Checkout (journeys/demand.json)',
      controls: ['email', 'cardNumber', 'cardExpiry', 'cardCvc', 'billingName', 'billingCountry', 'billingPostalCode', 'Pay', '← Back'],
      source: 'https://docs.stripe.com/payments/checkout/how-checkout-works',
    },
    {
      id: 'billing-portal', kind: 'flow', host: 'billing.stripe.com', path: '/p/session/{session}', status: 'done',
      demand: 'Cal.com, Dub, Postiz, Rallly and Twenty send customers to the billing portal', controls: ['Cancel plan', 'Renew plan', '← Return to {business name}'],
      source: 'https://docs.stripe.com/customer-management',
    },
    {
      // an Account Link's url (/setup/{account_link}) opens the onboarding session the page is (/setup/s/{session})
      id: 'connect-onboarding', kind: 'flow', host: 'connect.stripe.com', path: '/setup', status: 'done',
      demand: "Dub onboards its partners' connected accounts with Account Links", controls: ['Agree and submit', '← Return to platform'],
      source: 'https://docs.stripe.com/connect/hosted-onboarding',
    },
    {
      // Stripe.js, the client library an application's page loads: /v3/, /v3/stripe.js and /<release train>/stripe.js
      id: 'stripe-js', kind: 'content', host: 'js.stripe.com', path: '/', status: 'done',
      demand: "Dub's upgrade button loads Stripe.js and calls redirectToCheckout",
      source: 'https://docs.stripe.com/js',
    },
    {
      id: 'dashboard', kind: 'workspace', host: 'dashboard.stripe.com', path: '/', status: 'done',
      demand: 'World first-use customer inspection (twin-world/docs/contributing/first-use.md); operator setup: Public details; Radar lists for Dub add-to-stripe-fraud-value-lists.ts:3-7; sandbox funding for Open Autonomy world/model/scenario.ts:60,62',
      controls: ['Customers', 'Search customers', 'Search', 'Business name', 'Save', 'New list', 'Name', 'Alias', 'List type', 'Add', 'Add test funds', 'Amount'], source: 'https://docs.stripe.com/dashboard/basics',
    },
  ],
  resources: {
    'billing.meter': { refresh: { list: 'GetBillingMeters' },
      // source: spec:/components/schemas/billing.meter/properties/status "active"
      assigned: { object: { value: 'billing.meter' }, created: { now: true }, updated: { now: true }, livemode: { value: false }, status: { value: 'active' }, status_transitions: { value: { deactivated_at: null } },
        // source: https://docs.stripe.com/api/billing/meter/create "stripe_customer_id"
      // Where the page stops: omitted mappings use the creation example’s customer/value payload keys.
        customer_mapping: { value: { type: 'by_id', event_payload_key: 'stripe_customer_id' } }, value_settings: { value: { event_payload_key: 'value' } } },
      storedAs: 'billing_meter', idPrefix: 'mtr', notFound: "No such meter: '{id}'", ...states["billing.meter"], filters: ['status'],
    },
    'billing.meter_event': { refresh: { none: 'a meter event is written, never read: the API reads back only its meter’s summaries (GET /v1/billing/meters/{id}/event_summaries)' }, storedAs: 'billing_meter_event', idPrefix: 'mtr_evt' },
    payment_intent: { refresh: { list: 'GetPaymentIntents' },
      idPrefix: 'pi', ...states["payment_intent"],
      embeds: { customer: 'customer', latest_charge: 'charge', payment_method: 'payment_method', invoice: 'invoice' },
      filters: ['customer'],
    },
    // an update stores what it is given, nested objects whole, as the twin always has (Stripe merges
    // metadata keys; `update: 'replace'` keeps the twin's answer)
    // next_invoice_sequence, "The suffix of the customer's next invoice number" (docs.stripe.com/api/customers/object): one
    // past its numbered invoices (a finalized invoice is never deleted)
    customer: { refresh: { list: 'GetCustomers' }, idPrefix: 'cus', update: 'replace', ...states["customer"], filters: ['email'], counts: { next_invoice_sequence: { of: 'invoice', by: 'customer', present: 'number', plus: 1 } } },
    customer_balance_transaction: { refresh: { list: 'GetCustomersCustomerBalanceTransactions' }, parent: { param: 'customer', field: 'customer', resource: 'customer' }, idPrefix: 'cbtxn', ...states["customer_balance_transaction"], },
    customer_cash_balance_transaction: { refresh: { list: 'GetCustomersCustomerCashBalanceTransactions' }, parent: { param: 'customer', field: 'customer', resource: 'customer' }, storedAs: 'cash_balance_transaction', idPrefix: 'ccsbtxn', ...states["customer_cash_balance_transaction"], },
    // a card is chargeable at once; any other source waits for its owner to authorize it through its
    // flow, and is used up (single-use) or lapses
    // what a customer's sources list answers (a card, a bank account, a Source, an account) as one
    // resource over the stored sources; the card fields and an account's type/business_type are
    // attributes. A customer's bank account verifies as a payout account does.
    payment_source: { refresh: { none: 'a customer’s sources are listed only per customer, cards, bank accounts and Sources together (GET /v1/customers/{customer}/sources); the twin keeps them among the Sources, which no list reads' },
      storedAs: 'source',
      idPrefix: 'src', ...states["payment_source"],
    },
    source: { refresh: { none: 'Stripe lists no Sources: each is read by its id (GET /v1/sources/{source})' },
      idPrefix: 'src', ...states["source"],
    },
    // Connect OAuth's authorization codes: the row's id minted, the code's value drawn from the World's secret
    _oauth_code: { idPrefix: '', ids: '{n}' },
    charge: { refresh: { list: 'GetCharges' },
      idPrefix: 'ch', ...states["charge"],
      embeds: { customer: 'customer', payment_intent: 'payment_intent', invoice: 'invoice', balance_transaction: 'balance_transaction' },
      filters: ['customer', 'payment_intent'],
    },
    refund: { refresh: { list: 'GetRefunds' },
      idPrefix: 're',
      update: 'replace', ...states["refund"],
      embeds: { charge: 'charge', payment_intent: 'payment_intent', balance_transaction: 'balance_transaction' },
      filters: ['charge', 'payment_intent'],
    },
    setup_intent: { refresh: { list: 'GetSetupIntents' },
      idPrefix: 'seti',
      update: 'replace', ...states["setup_intent"],
      embeds: { customer: 'customer', payment_method: 'payment_method' },
      filters: ['customer', 'payment_method'],
    },
    payment_method: { refresh: { list: 'GetPaymentMethods' }, idPrefix: 'pm', ...states["payment_method"], embeds: { customer: 'customer' }, filters: ['customer', 'type'] },
    subscription: { refresh: { list: 'GetSubscriptions', complete: false },
      idPrefix: 'sub', ...states["subscription"],
      embeds: { customer: 'customer', latest_invoice: 'invoice', default_payment_method: 'payment_method', schedule: 'subscription_schedule' },
      // source: spec:/components/schemas/subscription/properties/items/description "List of subscription items, each with an attached price."
      // source: https://docs.stripe.com/api/subscriptions/object "subscription_items?subscription="
      collections: { items: { resource: 'subscription_item', by: 'subscription', list: { object: 'list', has_more: false, url: '/v1/subscription_items?subscription={id}' } } },
      filters: ['customer'],
    },
    subscription_item: { refresh: { none: 'subscription items are listed only per subscription (the list requires subscription), and each subscription answers its items in full (subscription.items)' }, idPrefix: 'si',
      // source: spec:/components/schemas/subscription_item/properties/price "price"
      embeds: { price: 'price' }, alwaysEmbedded: ['price'] },
    invoice: { refresh: { list: 'GetInvoices' },
      idPrefix: 'in', ...states["invoice"],
      embeds: { customer: 'customer', subscription: 'subscription', charge: 'charge', payment_intent: 'payment_intent' },
      filters: ['customer', 'status', 'subscription', 'collection_method'],
    },
    invoiceitem: { refresh: { list: 'GetInvoiceitems' }, idPrefix: 'ii', embeds: { customer: 'customer', price: 'price' }, filters: ['customer', 'invoice'], order: { field: 'date', direction: 'desc' } },
    'checkout.session': { refresh: { list: 'GetCheckoutSessions' },
      storedAs: 'checkout_session',
      idPrefix: 'cs', ...states["checkout.session"],
      filters: ['customer', 'payment_intent', 'subscription', 'status'],
      // the objects a session links to, as its x-expandableFields name them
      embeds: { customer: 'customer', invoice: 'invoice', payment_intent: 'payment_intent', payment_link: 'payment_link', setup_intent: 'setup_intent', subscription: 'subscription' },
    },
    ephemeral_key: { refresh: { none: 'an ephemeral key is answered once, by its create: the API has no read of one' }, idPrefix: 'ephkey' },
    // a mandate's status is the network's to move; nothing here moves it
    mandate: { refresh: { none: 'a mandate is read by its id (GET /v1/mandates/{mandate}): the API lists none' },
      idPrefix: 'mandate', ...states["mandate"],
    },
    dispute: { refresh: { list: 'GetDisputes' }, idPrefix: 'dp', update: 'replace', ...states["dispute"], embeds: { charge: 'charge', payment_intent: 'payment_intent' }, filters: ['charge', 'payment_intent'] },
    payout: { refresh: { list: 'GetPayouts' }, idPrefix: 'po', ...states["payout"], embeds: { balance_transaction: 'balance_transaction', destination: 'account' } },
    // the twin's ledger is seeded available; Stripe holds funds pending until their available_on
    balance_transaction: { refresh: { list: 'GetBalanceTransactions' },
      idPrefix: 'txn', ...states["balance_transaction"],
      filters: ['type', 'currency'],
    },
    // a coupon lapses at its redeem_by: "Date after which the coupon can no longer be redeemed", and `valid` is
    // "Taking account of the above properties, whether this coupon can still be applied to a customer" (the served
    // spec's coupon); the twin keeps no redemption count, so max_redemptions never lapses one
    coupon: { refresh: { list: 'GetCoupons' },
      idPrefix: 'coupon', update: 'replace', ...states["coupon"],
    },
    // switched on and off by an update (Stripe also lapses one at expires_at or when fully redeemed; the
    // twin keeps no redemption count or expiry)
    // source: https://docs.stripe.com/changelog/clover/2025-09-30/polymorphic-coupon "When you retrieve Promotion Codes, they don’t auto-expand the promotion.coupon field"
    // Before Clover the top-level coupon auto-expands; Clover omits that field in its view.
    promotion_code: { embeds: { coupon: 'coupon' }, alwaysEmbedded: ['coupon'], refresh: { list: 'GetPromotionCodes' },
      idPrefix: 'promo',
      update: 'replace',
      notFound: "No such promotion code: '{id}'", ...states["promotion_code"],
    },
    subscription_schedule: { refresh: { list: 'GetSubscriptionSchedules' },
      idPrefix: 'sub_sched',
      update: 'replace', ...states["subscription_schedule"],
      embeds: { customer: 'customer', subscription: 'subscription' },
      filters: ['customer', 'subscription'],
    },
    'entitlements.feature': { refresh: { list: 'GetEntitlementsFeatures' },
      storedAs: 'entitlements_feature', idPrefix: 'feat', notFound: "No such feature: '{id}'", ...states["entitlements.feature"],
    },
    // an advance answers advancing and the clock is ready once it has reached the time (./engine/test-clocks.ts)

    event: { refresh: { list: 'GetEvents', complete: false }, idPrefix: 'evt', filters: ['type'] },
    // disabled and re-enabled by an update's `disabled` (Stripe also disables one that keeps failing; the
    // twin counts no failures)
    webhook_endpoint: { refresh: { list: 'GetWebhookEndpoints' },
      idPrefix: 'we',
      notFound: "No such webhook endpoint: '{id}'", ...states["webhook_endpoint"],
    },
    account: {
      // source: spec:/components/schemas/account/properties/individual "person"
      embeds: { individual: 'person' }, alwaysEmbedded: ['individual'], refresh: { list: 'GetAccounts', complete: false }, idPrefix: 'acct', ...states["account"], },
    person: { refresh: { list: 'GetAccountsAccountPersons' }, idPrefix: 'person', ...states["person"], parent: { param: 'account', field: 'account', resource: 'account' } },
    // a capability lives in its account's capability map; requesting one leaves it pending, withdrawing it inactive
    capability: { refresh: { none: 'the twin keeps a capability in its account’s capabilities, which the accounts’ list reads back (GET /v1/accounts)' },
      idPrefix: 'cap', ...states["capability"],
    },
    // allow_redisplay and regulated_status belong to a card destination: consent and the issuer's
    // regulation, set when it is added, not a lifecycle
    external_account: { refresh: { none: 'an account answers its external accounts (account.external_accounts), which the accounts’ list reads back (GET /v1/accounts)' },
      idPrefix: 'ba', ...states["external_account"],
    },
    account_link: { refresh: { none: 'an account link is answered once, by its create: the API has no read of one' }, idPrefix: 'acctlink' },
    account_session: { refresh: { none: 'an account session is answered once, by its create: the API has no read of one' }, idPrefix: 'accts' },
    transfer: { refresh: { list: 'GetTransfers' }, idPrefix: 'tr', update: 'replace', filters: ['destination'] },
    transfer_reversal: { refresh: { list: 'GetTransfersIdReversals' }, parent: { param: 'id', field: 'transfer', resource: 'transfer' }, idPrefix: 'trr' },
    // refunded once fee refunds take its whole amount
    application_fee: { refresh: { list: 'GetApplicationFees' },
      idPrefix: 'fee', notFound: "No such application fee: '{id}'", filters: ['charge'], ...states["application_fee"],
    },
    fee_refund: { refresh: { list: 'GetApplicationFeesIdRefunds' }, parent: { param: 'id', field: 'fee', resource: 'application_fee' }, idPrefix: 'fr' },
    'apps.secret': { refresh: { none: 'secrets are listed only per scope (the list requires scope), which a root does not name' }, storedAs: 'apps_secret', idPrefix: 'apmc' },
    'billing_portal.session': { refresh: { none: 'a portal session is answered once, by its create: the API has no read of one' }, storedAs: 'billing_portal_session', idPrefix: 'bps', ...states["billing_portal.session"], },
    // is_default is Stripe's: the configuration the dashboard made first
    'billing_portal.configuration': { refresh: { list: 'GetBillingPortalConfigurations' },
      storedAs: 'billing_portal_configuration', idPrefix: 'bpc', notFound: "No such configuration: '{id}'", ...states["billing_portal.configuration"],
    },
    'tax.calculation': { refresh: { none: 'a calculation is read by its id (GET /v1/tax/calculations/{calculation}): the API lists none' }, storedAs: 'tax_calculation', idPrefix: 'taxcalc', notFound: "No such tax calculation: '{id}'" },
    'tax.transaction': { refresh: { none: 'a tax transaction is read by its id (GET /v1/tax/transactions/{transaction}): the API lists none' }, storedAs: 'tax_transaction', idPrefix: 'tax', notFound: "No such tax transaction: '{id}'", ...states["tax.transaction"], },
    // a review is open until it is closed; approving closes it, once
    review: { refresh: { list: 'GetReviews', complete: false },
      storedAs: 'radar_review',
      idPrefix: 'prv', ...states["review"],
    },
    'radar.value_list': { refresh: { list: 'GetRadarValueLists' }, storedAs: 'radar_value_list', idPrefix: 'rsl', notFound: "No such radar value list: '{id}'", ...states["radar.value_list"],
      // source: spec:/components/schemas/radar.value_list/properties/created/description "Time at which the object was created."
      assigned: { created: { now: true }, object: { value: 'radar.value_list' }, livemode: { value: false }, metadata: { value: {} },
        // source: spec:/components/schemas/radar.value_list/properties/created_by/description "The name or email address of the user who created this value list."
        // Where documentation stops: local API-key creates identify their synthetic account operator as twin.
        created_by: { value: 'twin' }, list_items: { value: { object: 'list', data: [], has_more: false, url: '/v1/radar/value_list_items' } } }, filters: ['alias'] },
    'radar.value_list_item': { refresh: { none: 'value list items are listed only per value list (the list requires value_list), and each list answers its items (radar.value_list.list_items)' }, storedAs: 'radar_value_list_item', idPrefix: 'rsli', notFound: "No such radar value list item: '{id}'" },
    'issuing.cardholder': { refresh: { list: 'GetIssuingCardholders' },
      storedAs: 'issuing_cardholder',
      idPrefix: 'ich',
      // source: spec:/components/schemas/issuing.cardholder/properties/created/description "Time at which the object was created."
      assigned: { created: { now: true }, object: { value: 'issuing.cardholder' }, livemode: { value: false }, metadata: { value: {} },
        // source: spec:/components/schemas/issuing_cardholder_requirements/properties/past_due/description "Array of fields that need to be collected"
        requirements: { value: { disabled_reason: null, past_due: [] } } },
      notFound: "No such cardholder: '{id}'", ...states["issuing.cardholder"],
      filters: ['status', 'type', 'email'],
    },
    'issuing.card': { refresh: { list: 'GetIssuingCards' },
      storedAs: 'issuing_card',
      idPrefix: 'ic',
      notFound: "No such card: '{id}'", ...states["issuing.card"],
      // source: spec:/components/schemas/issuing.card/properties/cardholder "issuing.cardholder"
      embeds: { cardholder: 'issuing.cardholder' }, alwaysEmbedded: ['cardholder'],
      filters: ['cardholder', 'status', 'type'],
    },
    'issuing.authorization': { refresh: { list: 'GetIssuingAuthorizations' }, storedAs: 'issuing_authorization', idPrefix: 'iauth', ...states["issuing.authorization"],
      // source: spec:/components/schemas/issuing.authorization/properties/card "issuing.card"
      embeds: { card: 'issuing.card', cardholder: 'issuing.cardholder' }, alwaysEmbedded: ['card'], filters: ['card', 'cardholder', 'status'], },
    'issuing.transaction': { refresh: { list: 'GetIssuingTransactions' }, storedAs: 'issuing_transaction', idPrefix: 'ipi', notFound: "No such transaction: '{id}'", ...states["issuing.transaction"], filters: ['card', 'cardholder'] },

    'treasury.outbound_payment': { refresh: { none: 'outbound payments are listed only per financial account (the list requires financial_account)' },
      storedAs: 'outbound_payment',
      idPrefix: 'obp',
      notFound: "No such outbound payment: '{id}'", ...states["treasury.outbound_payment"],
      filters: ['financial_account', 'status'],
    },
    'treasury.outbound_transfer': { refresh: { none: 'outbound transfers are listed only per financial account (the list requires financial_account)' },
      storedAs: 'outbound_transfer',
      idPrefix: 'obt',
      notFound: "No such outbound transfer: '{id}'", ...states["treasury.outbound_transfer"],
      filters: ['financial_account', 'status'],
    },
    'treasury.inbound_transfer': { refresh: { none: 'inbound transfers are listed only per financial account (the list requires financial_account)' },
      storedAs: 'inbound_transfer',
      idPrefix: 'ibt',
      notFound: "No such inbound transfer: '{id}'", ...states["treasury.inbound_transfer"],
      filters: ['financial_account', 'status'],
    },
    // received credits and debits are materialized by the network (test helpers the twin does not serve)
    'treasury.received_credit': { refresh: { none: 'received credits are listed only per financial account (the list requires financial_account)' }, storedAs: 'received_credit', idPrefix: 'rc', notFound: "No such received credit: '{id}'", ...states["treasury.received_credit"], filters: ['financial_account', 'status'] },
    'treasury.received_debit': { refresh: { none: 'received debits are listed only per financial account (the list requires financial_account)' }, storedAs: 'received_debit', idPrefix: 'rd', notFound: "No such received debit: '{id}'", ...states["treasury.received_debit"], filters: ['financial_account', 'status'] },
    // a ledger transaction is posted or left open by the flow that writes it; the network settles an open one
    'treasury.transaction': { refresh: { none: 'Treasury transactions are listed only per financial account (the list requires financial_account)' },
      storedAs: 'treasury_transaction', idPrefix: 'trxn', notFound: "No such treasury transaction: '{id}'", ...states["treasury.transaction"],
    },
    'treasury.transaction_entry': { refresh: { none: 'transaction entries are listed only per financial account (the list requires financial_account)' }, storedAs: 'treasury_transaction_entry', idPrefix: 'trxne', notFound: "No such transaction entry: '{id}'", ...states["treasury.transaction_entry"], },
    'financial_connections.session': { refresh: { none: 'a session is read by its id (GET /v1/financial_connections/sessions/{session}): the API lists none' }, storedAs: 'fc_session', idPrefix: 'fcsess' },
    // a linked account's transactions arrive posted here; the bank settles a pending one
    'financial_connections.transaction': { refresh: { none: 'transactions are listed only per linked account (the list requires account)' },
      storedAs: 'fc_transaction', idPrefix: 'fctxn', ...states["financial_connections.transaction"],
    },
    // archived (active=false) and restored by an update
    product: { refresh: { list: 'GetProducts' }, idPrefix: 'prod', update: 'replace', ...states["product"], },
    product_feature: {
      // source: spec:/components/schemas/product_feature/properties/entitlement_feature "entitlements.feature"
      embeds: { entitlement_feature: 'entitlements.feature' }, alwaysEmbedded: ['entitlement_feature'], refresh: { list: 'GetProductsProductFeatures' }, parent: { param: 'product', field: '_product', resource: 'product' }, idPrefix: 'prodft' },
    price: { refresh: { list: 'GetPrices', complete: false },
      idPrefix: 'price',
      update: 'replace', ...states["price"], embeds: { product: 'product' },
    },
  },
  // the webhooks Stripe's writes send (./semantics/shared.ts), each event's data and account rendered by ./semantics/events.ts
  events: { ...STRIPE_EVENTS, render: data, values },
  // a vendor-backed World's root: Stripe's webhooks sent to the World's ingest door, signed as Stripe signs every event
  // (Stripe-Signature: t=<seconds>,v1=<HMAC-SHA256 of "<t>.<body>">, docs.stripe.com/webhooks#verify-manually), the
  // event's type in its body and its object at data.object (docs.stripe.com/api/events/object); the types whose
  // resource neither the events' write names nor <resource>.created|updated|deleted say
  ingest: {
    scheme: { kind: 'timestamp-v1', header: 'Stripe-Signature' },
    type: { body: 'type' },
    object: 'data.object',
    types: {
      'checkout.session.completed': { resource: 'checkout.session' },
      'checkout.session.expired': { resource: 'checkout.session' },
      'charge.succeeded': { resource: 'charge' },
      'charge.failed': { resource: 'charge' },
      'charge.refunded': { resource: 'charge' },
      'payment_intent.requires_action': { resource: 'payment_intent' },
      'payment_intent.canceled': { resource: 'payment_intent' },
      'payment_method.automatically_updated': { resource: 'payment_method' },
      'invoice.payment_succeeded': { resource: 'invoice' },
      'invoice.payment_failed': { resource: 'invoice' },
      'invoice.voided': { resource: 'invoice' },
      'transfer.reversed': { resource: 'transfer' },
      'account.external_account.updated': { resource: 'external_account' },
      'account.external_account.created': { resource: 'external_account' },
      'account.external_account.deleted': { resource: 'external_account', deleted: true },
      'payout.paid': { resource: 'payout' },
      'payout.failed': { resource: 'payout' },
      'issuing_authorization.request': { resource: 'issuing.authorization' },
    },
  },
};
