// GENERATED by scripts/create-pack.ts --index: the handler map, by operationId, from the families' files (each
// handler named as its operation). Do not edit; add a handler to its family's file and generate again.
import type { Handler } from '@volter/world-core';
import * as operations from './operations.ts';

export const r2Semantics: Record<string, Handler> = {
  AbortMultipartUpload: operations.AbortMultipartUpload,
  CompleteMultipartUpload: operations.CompleteMultipartUpload,
  CopyObject: operations.CopyObject,
  CreateBucket: operations.CreateBucket,
  CreateMultipartUpload: operations.CreateMultipartUpload,
  DeleteBucket: operations.DeleteBucket,
  DeleteBucketCors: operations.DeleteBucketCors,
  DeleteObject: operations.DeleteObject,
  GetBucketCors: operations.GetBucketCors,
  GetBucketLifecycleConfiguration: operations.GetBucketLifecycleConfiguration,
  GetBucketLocation: operations.GetBucketLocation,
  GetObject: operations.GetObject,
  HeadBucket: operations.HeadBucket,
  HeadObject: operations.HeadObject,
  ListBuckets: operations.ListBuckets,
  ListMultipartUploads: operations.ListMultipartUploads,
  ListObjects: operations.ListObjects,
  ListObjectsV2: operations.ListObjectsV2,
  ListParts: operations.ListParts,
  PutBucketCors: operations.PutBucketCors,
  PutBucketLifecycleConfiguration: operations.PutBucketLifecycleConfiguration,
  PutObject: operations.PutObject,
  UploadPart: operations.UploadPart,
};
