// GENERATED by scripts/create-pack.ts (--init, --index): a fixed file. The kernel serves the discovery door, the clock,
// the World's doors, the vendor's screens and the API from the pack's parts (architecture, "The pack contract").
import { createPackFetch, type DerivedFetch, type DerivedSurface, type PackFetchOptions } from '@volter/world-core';
import surface from './generated/surface.gen.json' with { type: 'json' };
import { manifest } from './manifest.ts';
import { around } from './semantics/around.ts';
import { board } from './semantics/board.ts';
import * as doors from './semantics/doors.ts';
import { apiSemantics } from './semantics/index.ts';
import { screen as screen_siteverify } from './screens/siteverify.ts';
import { screen as screen_turnstile_api } from './screens/turnstile-api.ts';
import { screen as screen_turnstile_challenge } from './screens/turnstile-challenge.ts';

export function createApiLaneFetch(options: PackFetchOptions = {}): DerivedFetch {
  return createPackFetch({
    manifest,
    surface: surface as DerivedSurface,
    handlers: apiSemantics,
    doors,
    around,
    board,
    screens: { "siteverify": screen_siteverify, "turnstile-api": screen_turnstile_api, "turnstile-challenge": screen_turnstile_challenge },
  }, options);
}
