// GENERATED by scripts/create-pack.ts --index: the handler map, by operationId, from the families' files (each
// handler named as its operation). Do not edit; add a handler to its family's file and generate again.
import type { Handler } from '@volter/world-core';
import * as clients from './clients.ts';
import * as enterprise_connections from './enterprise_connections.ts';
import * as instance from './instance.ts';
import * as invitations from './invitations.ts';
import * as jwks from './jwks.ts';
import * as jwt_templates from './jwt_templates.ts';
import * as oauth_applications from './oauth_applications.ts';
import * as organization_permissions from './organization_permissions.ts';
import * as organization_roles from './organization_roles.ts';
import * as organizations from './organizations.ts';
import * as sessions from './sessions.ts';
import * as sign_in_tokens from './sign_in_tokens.ts';
import * as users from './users.ts';

export const clerkSemantics: Record<string, Handler> = {
  AssignPermissionToOrganizationRole: organization_roles.AssignPermissionToOrganizationRole,
  CreateEnterpriseConnection: enterprise_connections.CreateEnterpriseConnection,
  CreateInvitation: invitations.CreateInvitation,
  CreateJWTTemplate: jwt_templates.CreateJWTTemplate,
  CreateOAuthApplication: oauth_applications.CreateOAuthApplication,
  CreateOrganization: organizations.CreateOrganization,
  CreateOrganizationInvitation: organizations.CreateOrganizationInvitation,
  CreateOrganizationInvitationBulk: organizations.CreateOrganizationInvitationBulk,
  CreateOrganizationMembership: organizations.CreateOrganizationMembership,
  CreateOrganizationPermission: organization_permissions.CreateOrganizationPermission,
  CreateOrganizationRole: organization_roles.CreateOrganizationRole,
  CreateSessionToken: sessions.CreateSessionToken,
  CreateSignInToken: sign_in_tokens.CreateSignInToken,
  CreateUser: users.CreateUser,
  DeleteOrganization: organizations.DeleteOrganization,
  DeleteOrganizationMembership: organizations.DeleteOrganizationMembership,
  DeleteUser: users.DeleteUser,
  GetEnterpriseConnection: enterprise_connections.GetEnterpriseConnection,
  GetHandshakePayload: clients.GetHandshakePayload,
  GetInstanceOrganizationSettings: instance.GetInstanceOrganizationSettings,
  GetJWKS: jwks.GetJWKS,
  GetOrganization: organizations.GetOrganization,
  GetOrganizationInvitation: organizations.GetOrganizationInvitation,
  GetOrganizationPermission: organization_permissions.GetOrganizationPermission,
  GetOrganizationRole: organization_roles.GetOrganizationRole,
  GetSessionList: sessions.GetSessionList,
  GetUserList: users.GetUserList,
  GetUsersCount: users.GetUsersCount,
  ListInvitations: invitations.ListInvitations,
  ListOrganizationInvitations: organizations.ListOrganizationInvitations,
  ListOrganizationMemberships: organizations.ListOrganizationMemberships,
  ListOrganizationPermissions: organization_permissions.ListOrganizationPermissions,
  ListOrganizationRoles: organization_roles.ListOrganizationRoles,
  ListOrganizations: organizations.ListOrganizations,
  MergeOrganizationMetadata: organizations.MergeOrganizationMetadata,
  ReplaceOrganizationMetadata: organizations.ReplaceOrganizationMetadata,
  ReplaceUserMetadata: users.ReplaceUserMetadata,
  RevokeOrganizationInvitation: organizations.RevokeOrganizationInvitation,
  RevokeSession: sessions.RevokeSession,
  RevokeSignInToken: sign_in_tokens.RevokeSignInToken,
  UpdateEnterpriseConnection: enterprise_connections.UpdateEnterpriseConnection,
  UpdateInstanceOrganizationSettings: instance.UpdateInstanceOrganizationSettings,
  UpdateJWTTemplate: jwt_templates.UpdateJWTTemplate,
  UpdateOrganization: organizations.UpdateOrganization,
  UpdateOrganizationMembership: organizations.UpdateOrganizationMembership,
  UpdateOrganizationRole: organization_roles.UpdateOrganizationRole,
  UpdateUser: users.UpdateUser,
  UpdateUserMetadata: users.UpdateUserMetadata,
  UsersGetOrganizationMemberships: users.UsersGetOrganizationMemberships,
  createSession: sessions.createSession,
};
