// GENERATED by scripts/create-pack.ts (--init, --index): a fixed file. The kernel serves the discovery door, the clock,
// the World's doors, the vendor's screens and the API from the pack's parts (architecture, "The pack contract").
import { createPackFetch, type DerivedFetch, type DerivedSurface, type PackFetchOptions } from '@volter/world-core';
import surface from './generated/surface.gen.json' with { type: 'json' };
import { manifest } from './manifest.ts';
import { around } from './semantics/around.ts';
import * as doors from './semantics/doors.ts';
import { clerkSemantics } from './semantics/index.ts';
import { screen as screen_dashboard } from './screens/dashboard.tsx';
import { screen as screen_images } from './screens/images.ts';
import { createFapiLaneFetch, manifest as fapi_manifest } from '../fapi/src/index.ts';

export function createClerkFetch(options: PackFetchOptions = {}): DerivedFetch {
  return createPackFetch({
    manifest,
    surface: surface as DerivedSurface,
    handlers: clerkSemantics,
    doors,
    around,
    screens: { "dashboard": screen_dashboard, "images": screen_images },
    lanes: { "fapi": { fetch: createFapiLaneFetch(options), manifest: fapi_manifest } },
  }, options);
}
