// GENERATED by scripts/create-pack.ts (--init, --index): a fixed file. The kernel serves the discovery door, the clock,
// the World's doors, the vendor's screens and the API from the pack's parts (architecture, "The pack contract").
import { createPackFetch, type DerivedFetch, type DerivedSurface, type PackFetchOptions } from '@volter/world-core';
import surface from './generated/surface.gen.json' with { type: 'json' };
import { manifest } from './manifest.ts';
import * as doors from './semantics/doors.ts';
import { semantics } from './semantics/index.ts';
import { createAuthLaneFetch, manifest as auth_manifest } from '../auth/src/index.ts';
import { createRestLaneFetch, manifest as rest_manifest } from '../rest/src/index.ts';
import { createStorageLaneFetch, manifest as storage_manifest } from '../storage/src/index.ts';

export function createSupabaseFetch(options: PackFetchOptions = {}): DerivedFetch {
  return createPackFetch({
    manifest,
    surface: surface as DerivedSurface,
    handlers: semantics,
    doors,
    lanes: { "auth": { fetch: createAuthLaneFetch(options), manifest: auth_manifest }, "rest": { fetch: createRestLaneFetch(options), manifest: rest_manifest }, "storage": { fetch: createStorageLaneFetch(options), manifest: storage_manifest } },
  }, options);
}
