// GENERATED by scripts/create-pack.ts (--init, --index): a fixed file. The kernel serves the discovery door, the clock,
// the World's doors, the vendor's screens and the API from the pack's parts (architecture, "The pack contract").
import { createPackFetch, type DerivedFetch, type DerivedSurface, type PackFetchOptions } from '@volter/world-core';
import surface from './generated/surface.gen.json' with { type: 'json' };
import { manifest } from './manifest.ts';
import { around } from './semantics/around.ts';
import { clock } from './semantics/clock.ts';
import * as sockets from './semantics/sockets.ts';
import * as doors from './semantics/doors.ts';
import { slackSemantics } from './semantics/index.ts';
import { screen as screen_account } from './screens/account.tsx';
import { screen as screen_admin } from './screens/admin.tsx';
import { screen as screen_apps } from './screens/apps.tsx';
import { screen as screen_files } from './screens/files.ts';
import { screen as screen_get_started } from './screens/get-started.tsx';
import { screen as screen_incoming_webhooks } from './screens/incoming-webhooks.ts';
import { screen as screen_invite } from './screens/invite.tsx';
import { screen as screen_join } from './screens/join.tsx';
import { screen as screen_manage_apps } from './screens/manage-apps.tsx';
import { screen as screen_oauth } from './screens/oauth.tsx';
import { screen as screen_response_url } from './screens/response-url.ts';

export function createSlackFetch(options: PackFetchOptions = {}): DerivedFetch {
  return createPackFetch({
    manifest,
    surface: surface as DerivedSurface,
    handlers: slackSemantics,
    doors,
    around,
    clock,
    sockets,
    screens: { "account": screen_account, "admin": screen_admin, "apps": screen_apps, "files": screen_files, "get-started": screen_get_started, "incoming-webhooks": screen_incoming_webhooks, "invite": screen_invite, "join": screen_join, "manage-apps": screen_manage_apps, "oauth": screen_oauth, "response-url": screen_response_url },
  }, options);
}
