// GENERATED by scripts/create-pack.ts --index: the handler map, by operationId, from the families' files (each
// handler named as its operation). Do not edit; add a handler to its family's file and generate again.
import type { Handler } from '@volter/world-core';
import * as domains from './domains.ts';
import * as emails from './emails.ts';

export const resendSemantics: Record<string, Handler> = {
  "domains/create": domains.domains_create,
  "domains/get": domains.domains_get,
  "domains/list": domains.domains_list,
  "domains/remove": domains.domains_remove,
  "domains/update": domains.domains_update,
  "domains/verify": domains.domains_verify,
  "emails/get": emails.emails_get,
  "emails/get-receiving": emails.emails_get_receiving,
  "emails/list": emails.emails_list,
  "emails/list-receiving": emails.emails_list_receiving,
  "emails/send": emails.emails_send,
  "emails/send-batch": emails.emails_send_batch,
};
