// GENERATED by scripts/create-pack.ts (--init, --index): a fixed file. The kernel serves the discovery door, the clock,
// the World's doors, the vendor's screens and the API from the pack's parts (architecture, "The pack contract").
import { createPackFetch, type DerivedFetch, type DerivedSurface, type PackFetchOptions } from '@volter/world-core';
import surface from './generated/surface.gen.json' with { type: 'json' };
import { manifest } from './manifest.ts';
import { around } from './semantics/around.ts';
import { scenario } from './semantics/scenario.ts';
import * as doors from './semantics/doors.ts';
import { anthropicSemantics } from './semantics/index.ts';
import { screen as screen_api_keys } from './screens/api-keys.tsx';
import { screen as screen_login } from './screens/login.tsx';

export function createAnthropicFetch(options: PackFetchOptions = {}): DerivedFetch {
  return createPackFetch({
    manifest,
    surface: surface as DerivedSurface,
    handlers: anthropicSemantics,
    doors,
    around,
    scenario,
    screens: { "api-keys": screen_api_keys, "login": screen_login },
  }, options);
}
