// GENERATED by scripts/create-pack.ts --index: the handler map, by operationId, from the families' files (each
// handler named as its operation). Do not edit; add a handler to its family's file and generate again.
import type { Handler } from '@volter/world-core';
import * as auth from './auth.ts';
import * as codex from './codex.ts';
import * as wham from './wham.ts';

export const codexSemantics: Record<string, Handler> = {
  "auth.poll": auth.auth_poll,
  "auth.revoke": auth.auth_revoke,
  "auth.token": auth.auth_token,
  "auth.usercode": auth.auth_usercode,
  "codex.compact": codex.codex_compact,
  "codex.models": codex.codex_models,
  "codex.responses": codex.codex_responses,
  "wham.accounts_check": wham.wham_accounts_check,
  "wham.consume": wham.wham_consume,
  "wham.credits": wham.wham_credits,
  "wham.messages": wham.wham_messages,
  "wham.profile": wham.wham_profile,
  "wham.usage": wham.wham_usage,
};
