// GENERATED by scripts/create-pack.ts --index: the handler map, by operationId, from the families' files (each
// handler named as its operation). Do not edit; add a handler to its family's file and generate again.
import type { Handler } from '@volter/world-core';
import * as batch from './batch.ts';
import * as enqueue from './enqueue.ts';
import * as messages from './messages.ts';
import * as publish from './publish.ts';
import * as queues from './queues.ts';
import * as workflows from './workflows.ts';

export const qstashSemantics: Record<string, Handler> = {
  delete_v2_messages: messages.delete_v2_messages,
  delete_v2_workflows_runs_workflowrunid: workflows.delete_v2_workflows_runs_workflowrunid,
  get_v2_messages_messageid: messages.get_v2_messages_messageid,
  post_v2_batch: batch.post_v2_batch,
  post_v2_enqueue_queuename_destination: enqueue.post_v2_enqueue_queuename_destination,
  post_v2_publish_destination: publish.post_v2_publish_destination,
  post_v2_queues: queues.post_v2_queues,
};
