// GENERATED by scripts/create-pack.ts (--init, --index): a fixed file. The kernel serves the discovery door, the clock,
// the World's doors, the vendor's screens and the API from the pack's parts (architecture, "The pack contract").
import { createPackFetch, type DerivedFetch, type DerivedSurface, type PackFetchOptions } from '@volter/world-core';
import surface from './generated/surface.gen.json' with { type: 'json' };
import { manifest } from './manifest.ts';
import { around } from './semantics/around.ts';
import { upstashSemantics } from './semantics/index.ts';
import { createApiLaneFetch, manifest as api_manifest } from '../api/src/index.ts';
import { createQstashLaneFetch, manifest as qstash_manifest } from '../qstash/src/index.ts';

export function createUpstashFetch(options: PackFetchOptions = {}): DerivedFetch {
  return createPackFetch({
    manifest,
    surface: surface as unknown as DerivedSurface,
    handlers: upstashSemantics,
    around,
    lanes: { "api": { fetch: createApiLaneFetch(options), manifest: api_manifest }, "qstash": { fetch: createQstashLaneFetch(options), manifest: qstash_manifest } },
  }, options);
}
