// GENERATED by scripts/create-pack.ts (--init, --index): a fixed file. The kernel serves the discovery door, the clock,
// the World's doors, the vendor's screens and the API from the pack's parts (architecture, "The pack contract").
import { createPackFetch, type DerivedFetch, type DerivedSurface, type PackFetchOptions } from '@volter/world-core';
import surface from './generated/surface.gen.json' with { type: 'json' };
import { manifest } from './manifest.ts';
import { around } from './semantics/around.ts';
import { clock } from './semantics/clock.ts';
import * as doors from './semantics/doors.ts';
import { resendSemantics } from './semantics/index.ts';
import { screen as screen_emails } from './screens/emails.tsx';
import { screen as screen_inbound_cdn } from './screens/inbound-cdn.ts';

export function createResendFetch(options: PackFetchOptions = {}): DerivedFetch {
  return createPackFetch({
    manifest,
    surface: surface as DerivedSurface,
    handlers: resendSemantics,
    doors,
    around,
    clock,
    screens: { "emails": screen_emails, "inbound-cdn": screen_inbound_cdn },
  }, options);
}
