// GENERATED by scripts/create-pack.ts (--init, --index): a fixed file. The kernel serves the discovery door, the clock,
// the World's doors, the vendor's screens and the API from the pack's parts (architecture, "The pack contract").
import { createPackFetch, type DerivedFetch, type DerivedSurface, type PackFetchOptions } from '@volter/world-core';
import surface from './generated/surface.gen.json' with { type: 'json' };
import { manifest } from './manifest.ts';
import { graphql } from './semantics/graphql.ts';
import schema from './generated/graphql-sdl.gen.json' with { type: 'json' };
import graphqlSurface from './generated/graphql.gen.json' with { type: 'json' };
import * as doors from './semantics/doors.ts';
import { linearSemantics } from './semantics/index.ts';
import { screen as screen_authorize } from './screens/authorize.tsx';
import { screen as screen_workspace } from './screens/workspace.tsx';

export function createLinearFetch(options: PackFetchOptions = {}): DerivedFetch {
  return createPackFetch({
    manifest,
    surface: surface as DerivedSurface,
    handlers: linearSemantics,
    doors,
    graphql: { ...graphql, operations: graphqlSurface.operations as NonNullable<typeof graphql.operations>, sdl: schema.sdl },
    screens: { "authorize": screen_authorize, "workspace": screen_workspace },
  }, options);
}
