// GENERATED by scripts/create-pack.ts --index: the handler map, by operationId, from the families' files (each
// handler named as its operation). Do not edit; add a handler to its family's file and generate again.
import type { Handler } from '@volter/world-core';
import * as assistants from './assistants.ts';
import * as audio from './audio.ts';
import * as chat from './chat.ts';
import * as files from './files.ts';
import * as images from './images.ts';
import * as models from './models.ts';
import * as moderations from './moderations.ts';
import * as responses from './responses.ts';
import * as threads from './threads.ts';
import * as vector_stores from './vector_stores.ts';

export const openaiSemantics: Record<string, Handler> = {
  cancelResponse: responses.cancelResponse,
  cancelRun: threads.cancelRun,
  createAssistant: assistants.createAssistant,
  createChatCompletion: chat.createChatCompletion,
  createFile: files.createFile,
  createImage: images.createImage,
  createImageEdit: images.createImageEdit,
  createMessage: threads.createMessage,
  createModeration: moderations.createModeration,
  createResponse: responses.createResponse,
  createRun: threads.createRun,
  createSpeech: audio.createSpeech,
  createThread: threads.createThread,
  createTranscription: audio.createTranscription,
  createVectorStore: vector_stores.createVectorStore,
  downloadFile: files.downloadFile,
  getChatCompletionMessages: chat.getChatCompletionMessages,
  getResponse: responses.getResponse,
  getRunStep: threads.getRunStep,
  listInputItems: responses.listInputItems,
  listModels: models.listModels,
  listRunSteps: threads.listRunSteps,
  modifyAssistant: assistants.modifyAssistant,
  retrieveModel: models.retrieveModel,
  submitToolOuputsToRun: threads.submitToolOuputsToRun,
};
