// THE DASHBOARD — dashboard.stripe.com's pages an operator sets what Stripe's API cannot (docs/contributing/architecture.md,
// "Screens": a workspace): Public details (/settings/public) and the Connect OAuth settings
// (/settings/connect/onboarding-options/oauth), Radar lists and test Issuing funding.
// The operator controls prepare the cited real application calls; other Dashboard pages answer Stripe's 404.
//
// THE DASHBOARD'S PUBLIC DETAILS — a workspace page (docs/contributing/architecture.md, "Screens") of the Dashboard
// (manifest screen `dashboard`), at dashboard.stripe.com/settings/public: Settings → Business → Public details, where
// the operator sets what their customers see ("Public Details → Business Settings",
// support.stripe.com/questions/update-account-name-shown-in-the-dashboard). Its business name is the account's
// `business_profile.name`, "The customer-facing business name" (docs.stripe.com/api/accounts/object), and it is the
// name Checkout shows: "You can change a Checkout page's name by modifying the Business name field"
// (docs.stripe.com/payments/checkout/customization/appearance). Stripe's API has no call that changes the platform's
// own account (POST /v1/accounts/{account} updates a connected one), so this page is the only way to the act, and
// saving it writes the platform account's stored record (../engine/connect.ts), which GET /v1/account,
// Checkout and the customer portal then read. The Dashboard's account name (`settings.dashboard.display_name`,
// Settings → Account) is a separate, internal setting, "for internal use only" (the same support article), and this
// page does not touch it. Authored from plain markup under Stripe's type; nothing of Stripe's page is copied.
//
// Where the documentation stops and the twin decides: the page holds the business name only (the real page's
// support details, website and statement descriptor are not modelled here); the name is required and at most 5000
// characters (the spec's bound on business_profile.name), which the browser holds the field to and the page checks
// again for a client that is not a browser; no sign-in guards the page. The form posts to the page's own address
// and the save redirects to its own path. Saving is an update of an account that exists (the first save included, though
// the twin stores the platform's record only then), so every save is sent as account.updated.
//
// THE DASHBOARD'S CONNECT OAUTH SETTINGS — a workspace page (docs/contributing/architecture.md, "Screens") of the
// Dashboard (manifest screen `dashboard`), at dashboard.stripe.com/settings/connect/onboarding-options/oauth, where a
// platform starts an OAuth integration: "Enable onboarding accounts with OAuth", "Copy your client_id, a unique
// identifier for your platform that's generated by Stripe", and "Set your redirect_uri ... You must specify all redirect
// URLs in your platform settings. If you don't include the redirect_uri parameter in your request, Stripe defaults to
// using the first address you've configured" (docs.stripe.com/connect/oauth-standard-accounts). The test client_id
// "allows you to: Set your redirect_uri to a non-HTTPS URL; Set your redirect_uri to localhost"
// (docs.stripe.com/connect/testing#using-oauth). Stripe's API has no call that reads or changes these settings (GET
// /v1/account does not carry the client_id), so this page is the only way to them, and connect.stripe.com/oauth/authorize
// (./connect-oauth.tsx) reads what it saves. Authored from plain markup under Stripe's type; nothing of Stripe's page is
// copied.
//
// Where the documentation stops and the twin decides: the World has one platform, and its test client_id is
// `ca_twin_self` (PLATFORM_CLIENT_ID; the platform account is acct_twin_self), the same in every World, shown on the
// page in an element a runner reads (data-testid="connect-client-id"). OAuth starts disabled. The page is served at
// the docs' address, at /test/… (the docs' test-mode link) and at /settings/connect (the address Cal.com's setup
// guide gives). The redirect URIs are one form field, one per line (or comma-separated, as the reference describes
// them), saved whole: each an absolute http or https URL without a fragment; http and localhost are allowed, as the
// test client_id allows them. No sign-in guards the page. The form posts to the
// page's own address and the save redirects to it.
import type { HandlerContext } from '@volter/world-core';
import { flowPage } from '@volter/world-ui';
import { VL } from '../engine/radar.ts';
import { nowUnix } from '../engine/stripe.ts';
import type { Row } from '../engine/common.ts';
import { platformAccountDefault } from '../engine/connect.ts';
import { publicBusinessName } from '../engine/display.ts';
import { PLATFORM_ACCOUNT_ID } from '../engine/stripe.ts';
import { formOf, notFound } from './shared.tsx';
import { created } from '../semantics/shared.ts';
const redirect = (path: string): Response => new Response(null, { status: 303, headers: { location: path } });
const invalid = (message: string): Response => flowPage({ css: [], title: 'Stripe', status: 400, body: <main><p role="alert">{message}</p></main> });

const PUBLIC_DETAILS_PATH = '/settings/public';
const MAX_NAME = 5000;

const DETAILS_CSS = `
* { box-sizing: border-box; }
body { margin: 0; background: #f6f8fa; color: #1a1f36; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Ubuntu, sans-serif; font-size: 14px; }
.pd { max-width: 640px; margin: 48px auto; padding: 0 16px; }
.pd h1 { font-size: 28px; margin: 16px 0 4px; }
.pd-lead { color: #697386; margin: 0 0 24px; }
.pd-card { background: #ffffff; border: 1px solid #e3e8ee; border-radius: 8px; padding: 24px; }
.pd-card label { display: block; font-weight: 600; margin-bottom: 6px; }
.pd-card small { display: block; color: #697386; margin-bottom: 8px; }
.pd-card input { width: 100%; padding: 8px 10px; border: 1px solid #c1c9d2; border-radius: 6px; font: inherit; }
.pd-actions { margin-top: 20px; display: flex; justify-content: flex-end; }
.pd-actions button { background: #635bff; color: #ffffff; border: 0; border-radius: 6px; padding: 8px 16px; font: inherit; font-weight: 600; cursor: pointer; }
.pd-notice { padding: 10px 12px; border-radius: 6px; margin-bottom: 16px; }
.pd-error { background: #fff0f3; color: #df1b41; }
.pd-saved { background: #e7f8ef; color: #0e6245; }
`;

function detailsPage(account: Row | undefined, opts: { value?: string; error?: string; saved?: boolean } = {}): Response {
  const named = (account?.business_profile as Row | undefined)?.name;
  const value = opts.value ?? (typeof named === 'string' ? named : '');
  return flowPage({
    title: 'Public details – Stripe',
    css: [DETAILS_CSS],
    ...(opts.error ? { status: 400 } : {}),
    body: (
      <main className="pd">
        <h1>Public details</h1>
        <p className="pd-lead">What your customers see on Checkout, the customer portal, receipts and invoices. Currently shown: <strong data-testid="public-business-name">{publicBusinessName(account)}</strong></p>
        {opts.error ? <p className="pd-notice pd-error" role="alert">{opts.error}</p> : null}
        {opts.saved ? <p className="pd-notice pd-saved" role="status">Your public details were saved.</p> : null}
        <form className="pd-card" method="post">
          <label htmlFor="business_name">Business name</label>
          <small>The name customers see when they pay you.</small>
          <input id="business_name" name="business_name" autoComplete="organization" defaultValue={value} required maxLength={MAX_NAME} />
          <div className="pd-actions"><button type="submit">Save</button></div>
        </form>
      </main>
    ),
  });
}

/** Save the business name on the platform's own account: the stored record, made from Stripe's default the first
 *  time anything is saved, and otherwise changed in place (its other public details kept). */
async function save(ctx: HandlerContext, name: string): Promise<void> {
  const held = ctx.get('account', PLATFORM_ACCOUNT_ID);
  const profile = { business_profile: { ...(((held ?? platformAccountDefault()).business_profile as Row | undefined) ?? {}), name } };
  await (held ? ctx.write('account', PLATFORM_ACCOUNT_ID, profile, 'account.update') : created(ctx, 'account', { ...platformAccountDefault(), ...profile }, {}, { operation: 'account.update' }));
}

/** What the page says of a name no browser sends (the field is required and bounded), for a client that sends it. */
function nameRefused(name: string): string | undefined {
  return !name ? 'Enter your business name.' : name.length > MAX_NAME ? `Your business name must be at most ${MAX_NAME} characters.` : undefined;
}

async function publicDetails(ctx: HandlerContext): Promise<Response> {
  const request = ctx.call.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' && request.method !== 'POST') return notFound();
  const form = request.method === 'POST' ? await formOf(request.clone()) : {};
  if (request.method === 'GET') return detailsPage(ctx.get('account', PLATFORM_ACCOUNT_ID), { saved: url.searchParams.has('saved') });
  const name = (form.business_name ?? '').trim();
  const refused = nameRefused(name);
  if (refused) return detailsPage(ctx.get('account', PLATFORM_ACCOUNT_ID), { value: form.business_name ?? '', error: refused });
  await save(ctx, name);
  // a query-only reference: the page's own path, wherever it is mounted and with or without its trailing slash
  return new Response(null, { status: 303, headers: { location: '?saved=1' } });
}

/** Dashboard settings, Radar list creation and test Issuing funding; other pages answer Stripe's 404. */
export async function screen(ctx: HandlerContext): Promise<Response> {
  const path = new URL(ctx.call.request.url).pathname.replace(/\/+$/, '');
  // The twin's declared workspace entry opens its implemented Public details page; this authored choice does not
  // reproduce Stripe's Dashboard home. The request's public base retains the World mount when the console frames it.
  if (path === '' && ['GET', 'HEAD'].includes(ctx.call.request.method)) return redirect(`${ctx.publicBase}${PUBLIC_DETAILS_PATH}`);
  // source: https://docs.stripe.com/radar/lists "Use the Dashboard or the API to create lists."
  // source: https://docs.stripe.com/radar/lists "Enter a name for the list"
  // source: https://docs.stripe.com/radar/lists "Select the type of list to create."
  // source: https://docs.stripe.com/radar/lists "Click Add to save your new list."
  // Where the documentation stops: it names Dashboard controls, not their browser request routes or form wire.
  // This authored page uses /radar/lists for GET and POST, /radar/lists/{id} for its redirect/detail address,
  // and a 303 redirect after saving. The HTML field names name, alias and item_type are the twin's choices;
  // item_type values are the pinned API's enums, not published Dashboard form values. The alias fallback's
  // lowercase/underscore algorithm is also authored; Stripe says it generates an alias but gives no algorithm.
  if (/^\/radar\/lists(?:\/[^/]+)?$/.test(path)) {
    if (ctx.call.request.method === 'POST') {
      const form = await formOf(ctx.call.request);
      const types = ['string', 'case_sensitive_string', 'card_fingerprint', 'card_bin', 'customer_id', 'email', 'ip_address', 'country', 'sepa_debit_fingerprint', 'us_bank_account_fingerprint'];
      if (!form.name?.trim() || !types.includes(form.item_type ?? '')) return invalid('Enter a name and select a list type.');
      const alias = form.alias?.trim() || form.name.toLowerCase().replace(/[^a-z0-9]+/g, '_');
      // Where the page stops: an operator has no login identity in the World; created_by is its synthetic operator.
      const list = await created(ctx, VL, { name: form.name.trim(), alias, item_type: form.item_type }, {
        created_by: 'twin', livemode: false, metadata: {},
        list_items: { object: 'list', data: [], has_more: false, url: '/v1/radar/value_list_items' },
      });
      await ctx.write(VL, String(list.id), { list_items: { object: 'list', data: [], has_more: false, url: `/v1/radar/value_list_items?value_list=${list.id}` } }, 'radar.value_list.updated');
      return redirect(`/radar/lists/${list.id}`);
    }
    return flowPage({ css: [], title: 'Lists – Radar – Stripe', body: <main><h1>Radar Lists</h1><form method="post" action="/radar/lists"><h2>New list</h2><label>Name<input name="name" required /></label><label>Alias<input name="alias" /></label><label>List type<select name="item_type"><option value="customer_id">Customer ID</option><option value="email">Email</option><option value="card_fingerprint">Card fingerprint</option><option value="ip_address">IP address</option><option value="string">String</option></select></label><button>Add</button></form><ul>{ctx.rows(VL).map(row => <li key={String(row.id)}>{String(row.name)} ({String(row.alias)})</li>)}</ul></main> });
  }
  // source: https://docs.stripe.com/issuing/testing "Before you create test transactions, you must add test funds to the Issuing balance on your account."
  // source: https://docs.stripe.com/issuing/testing "You can create test top-ups in the Dashboard, or with the Top-ups API"
  // Where the documentation stops: it states the Dashboard funding act, not a browser request path or form wire.
  // The authored GET/POST address and 303 redirect are /test/issuing/balance. The form name amount, its positive
  // integer validation and its units (USD cents for this US sandbox) are the twin's choices, not published form
  // fields. Its POST records the balance change in the vendor ledger, with source=null (permitted by the pinned
  // schema) and immediate availability for this sandbox control; the page states neither that source nor timing.
  // No private Topup object is seeded or answered, and the uncalled Top-ups API remains the gap.
  if (path === '/test/issuing/balance') {
    if (ctx.call.request.method === 'POST') {
      const form = await formOf(ctx.call.request);
      const amount = Number(form.amount);
      if (!Number.isInteger(amount) || amount <= 0) return invalid('Enter a positive amount in cents.');
      await created(ctx, 'balance_transaction', {}, { amount, currency: 'usd', fee: 0, net: amount, type: 'topup', reporting_category: 'topup', source: null, status: 'available', balance_type: 'issuing', available_on: Number(nowUnix(ctx.occurredAt)), fee_details: [] });
      return redirect('/test/issuing/balance');
    }
    return flowPage({ css: [], title: 'Test Issuing balance – Stripe', body: <main><h1>Test Issuing balance</h1><form method="post"><label>Amount<input name="amount" type="number" min="1" required /></label><button>Add test funds</button></form></main> });
  }
  return path === PUBLIC_DETAILS_PATH ? publicDetails(ctx) : notFound();
}
