// GENERATED by scripts/create-pack.ts --index: the handler map, by operationId, from the families' files (each
// handler named as its operation). Do not edit; add a handler to its family's file and generate again.
import type { Handler } from '@volter/world-core';
import * as account from './account.ts';
import * as account_links from './account_links.ts';
import * as accounts from './accounts.ts';
import * as apps from './apps.ts';
import * as balance from './balance.ts';
import * as balance_transactions from './balance_transactions.ts';
import * as billing_portal from './billing_portal.ts';
import * as charges from './charges.ts';
import * as checkout from './checkout.ts';
import * as coupons from './coupons.ts';
import * as customers from './customers.ts';
import * as invoice_payments from './invoice_payments.ts';
import * as invoices from './invoices.ts';
import * as issuing from './issuing.ts';
import * as payment_intents from './payment_intents.ts';
import * as payment_methods from './payment_methods.ts';
import * as payouts from './payouts.ts';
import * as prices from './prices.ts';
import * as products from './products.ts';
import * as promotion_codes from './promotion_codes.ts';
import * as radar from './radar.ts';
import * as refunds from './refunds.ts';
import * as subscriptions from './subscriptions.ts';
import * as test_helpers from './test_helpers.ts';
import * as transfers from './transfers.ts';
import * as webhook_endpoints from './webhook_endpoints.ts';

export const stripeSemantics: Record<string, Handler> = {
  DeleteSubscriptionsSubscriptionExposedId: subscriptions.DeleteSubscriptionsSubscriptionExposedId,
  DeleteSubscriptionsSubscriptionExposedIdDiscount: subscriptions.DeleteSubscriptionsSubscriptionExposedIdDiscount,
  GetAccount: account.GetAccount,
  GetAccountsAccountExternalAccounts: accounts.GetAccountsAccountExternalAccounts,
  GetAppsSecretsFind: apps.GetAppsSecretsFind,
  GetBalance: balance.GetBalance,
  GetBalanceTransactions: balance_transactions.GetBalanceTransactions,
  GetBillingPortalConfigurations: billing_portal.GetBillingPortalConfigurations,
  GetCharges: charges.GetCharges,
  GetChargesCharge: charges.GetChargesCharge,
  GetCheckoutSessionsSessionLineItems: checkout.GetCheckoutSessionsSessionLineItems,
  GetCustomersCustomer: customers.GetCustomersCustomer,
  GetCustomersSearch: customers.GetCustomersSearch,
  GetInvoicePayments: invoice_payments.GetInvoicePayments,
  GetInvoicesInvoice: invoices.GetInvoicesInvoice,
  GetIssuingCardsCard: issuing.GetIssuingCardsCard,
  GetPaymentMethodsPaymentMethod: payment_methods.GetPaymentMethodsPaymentMethod,
  GetPayouts: payouts.GetPayouts,
  GetPrices: prices.GetPrices,
  GetPricesPrice: prices.GetPricesPrice,
  GetProducts: products.GetProducts,
  GetPromotionCodes: promotion_codes.GetPromotionCodes,
  GetSubscriptions: subscriptions.GetSubscriptions,
  GetSubscriptionsSubscriptionExposedId: subscriptions.GetSubscriptionsSubscriptionExposedId,
  PostAccountLinks: account_links.PostAccountLinks,
  PostAccounts: accounts.PostAccounts,
  PostAccountsAccountLoginLinks: accounts.PostAccountsAccountLoginLinks,
  PostAppsSecrets: apps.PostAppsSecrets,
  PostAppsSecretsDelete: apps.PostAppsSecretsDelete,
  PostBillingPortalConfigurations: billing_portal.PostBillingPortalConfigurations,
  PostBillingPortalSessions: billing_portal.PostBillingPortalSessions,
  PostCheckoutSessions: checkout.PostCheckoutSessions,
  PostCoupons: coupons.PostCoupons,
  PostCustomers: customers.PostCustomers,
  PostCustomersCustomer: customers.PostCustomersCustomer,
  PostInvoices: invoices.PostInvoices,
  PostInvoicesCreatePreview: invoices.PostInvoicesCreatePreview,
  PostInvoicesInvoicePay: invoices.PostInvoicesInvoicePay,
  PostInvoicesInvoiceVoid: invoices.PostInvoicesInvoiceVoid,
  PostIssuingAuthorizationsAuthorizationApprove: issuing.PostIssuingAuthorizationsAuthorizationApprove,
  PostIssuingAuthorizationsAuthorizationDecline: issuing.PostIssuingAuthorizationsAuthorizationDecline,
  PostIssuingCards: issuing.PostIssuingCards,
  PostIssuingCardsCard: issuing.PostIssuingCardsCard,
  PostPaymentIntents: payment_intents.PostPaymentIntents,
  PostPaymentIntentsIntentCancel: payment_intents.PostPaymentIntentsIntentCancel,
  PostPaymentMethodsPaymentMethodDetach: payment_methods.PostPaymentMethodsPaymentMethodDetach,
  PostPayouts: payouts.PostPayouts,
  PostPrices: prices.PostPrices,
  PostProducts: products.PostProducts,
  PostPromotionCodes: promotion_codes.PostPromotionCodes,
  PostRadarValueListItems: radar.PostRadarValueListItems,
  PostRefunds: refunds.PostRefunds,
  PostSubscriptionsSubscriptionExposedId: subscriptions.PostSubscriptionsSubscriptionExposedId,
  PostTestHelpersIssuingAuthorizations: test_helpers.PostTestHelpersIssuingAuthorizations,
  PostTestHelpersIssuingAuthorizationsAuthorizationCapture: test_helpers.PostTestHelpersIssuingAuthorizationsAuthorizationCapture,
  PostTransfers: transfers.PostTransfers,
  PostWebhookEndpoints: webhook_endpoints.PostWebhookEndpoints,
};
