// GENERATED by scripts/create-pack.ts (--init, --index): a fixed file. The kernel serves the discovery door, the clock,
// the World's doors, the vendor's screens and the API from the pack's parts (architecture, "The pack contract").
import { createPackFetch, type DerivedFetch, type DerivedSurface, type PackFetchOptions } from '@volter/world-core';
import surface from './generated/surface.gen.json' with { type: 'json' };
import { manifest } from './manifest.ts';
import { around } from './semantics/around.ts';
import { clock } from './semantics/clock.ts';
import * as doors from './semantics/doors.ts';
import { r2Semantics } from './semantics/index.ts';
import { screen as screen_api_tokens } from './screens/api-tokens.tsx';
import { screen as screen_dashboard } from './screens/dashboard.tsx';
import { screen as screen_login } from './screens/login.tsx';
import { screen as screen_profile_api_tokens } from './screens/profile-api-tokens.tsx';
import { screen as screen_workers_and_pages } from './screens/workers-and-pages.tsx';

export function createR2LaneFetch(options: PackFetchOptions = {}): DerivedFetch {
  return createPackFetch({
    manifest,
    surface: surface as DerivedSurface,
    handlers: r2Semantics,
    doors,
    around,
    clock,
    screens: { "api-tokens": screen_api_tokens, "dashboard": screen_dashboard, "login": screen_login, "profile-api-tokens": screen_profile_api_tokens, "workers-and-pages": screen_workers_and_pages },
  }, options);
}
