import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
if (!process.env.VOLTER_WORLD) throw new Error('Publisher qualification requires its owned World');
const pack = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const require = createRequire(join(pack.work, 'package.json'));
const { assessPack } = await import(pathToFileURL(require.resolve('@volter/twin-standard')).href);
const report = { ...await assessPack(pack.packDir, { consumer: pack.consumer }), integrity: pack.integrity, sourceCommit: pack.sourceCommit, preparation: 'prepared-assessment.json' };
mkdirSync(pack.release, { recursive: true });
writeFileSync(join(pack.release, 'qualification.json'), JSON.stringify(report, null, 2) + '\n');
console.log(JSON.stringify({ ready: report.ready, package: report.package, version: report.version, integrity: report.integrity, report: join(pack.release, 'qualification.json'), browser: 'Independent catalog assessment after publication' }));
process.exit(report.ready ? 0 : 1);
