import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { selectedPack } from './selected-pack.mjs';
import { assessPack } from '@volter/twin-standard';
if (!process.env.VOLTER_WORLD) throw new Error('Publisher qualification requires its owned World');
const pack = selectedPack();
const report = await assessPack(pack.directory);
mkdirSync(pack.release, { recursive: true });
writeFileSync(join(pack.release, 'qualification.json'), JSON.stringify(report, null, 2) + '\n');
console.log(JSON.stringify({ ready: report.ready, package: report.package, version: report.version, report: join(pack.release, 'qualification.json'), browser: 'Independent catalog assessment after publication' }));
process.exit(report.ready ? 0 : 1);
