import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { compilePackFacts } from '@volter/twin-standard';
import { selectedPack } from './selected-pack.mjs';
assert.ok(process.env.VOLTER_WORLD, 'pack builds run through a World');
const pack = selectedPack();
const result = spawnSync('node', ['scripts/compile.mjs', pack.directory], { stdio: 'inherit' });
assert.equal(result.status, 0, 'compiled build failed');
const facts = await compilePackFacts([{ vendor: pack.vendor, dir: pack.directory }]);
assert.deepEqual(facts.undeclared, []);
assert.deepEqual(Object.keys(facts.packs), [pack.vendor]);
mkdirSync(join(pack.directory, 'generated'), { recursive: true });
writeFileSync(join(pack.directory, 'generated/pack-facts.json'), JSON.stringify(facts, null, 2) + '\n');
console.log(JSON.stringify({ vendor: pack.vendor, package: pack.manifest.name, version: pack.manifest.version, built: true }));
