// GENERATED by scripts/create-pack.ts (--init, --index): a fixed file. The kernel serves the discovery door, the clock,
// the World's doors, the vendor's screens and the API from the pack's parts (architecture, "The pack contract").
import { createPackFetch, type DerivedFetch, type DerivedSurface, type PackFetchOptions } from '@volter/world-core';
import surface from './generated/surface.gen.json' with { type: 'json' };
import { manifest } from './manifest.ts';
import { around } from './semantics/around.ts';
import { scenario } from './semantics/scenario.ts';
import * as sockets from './semantics/sockets.ts';
import { codexSemantics } from './semantics/index.ts';
import { screen as screen_authorize } from './screens/authorize.tsx';
import { screen as screen_device } from './screens/device.tsx';

export function createCodexLaneFetch(options: PackFetchOptions = {}): DerivedFetch {
  return createPackFetch({
    manifest,
    surface: surface as DerivedSurface,
    handlers: codexSemantics,
    around,
    scenario,
    sockets,
    screens: { "authorize": screen_authorize, "device": screen_device },
  }, options);
}
