// GENERATED by scripts/create-pack.ts (--init, --index): a fixed file. The kernel serves the vendor's discovery door and
// sends each request to the lane its manifest's routes name (architecture, "Other wires: lanes").
import { createVendorFetch, type DerivedFetch, type PackFetchOptions } from '@volter/world-core';
import { manifest } from './manifest.ts';
import { createApiLaneFetch, manifest as api_manifest } from '../api/src/index.ts';
import { createR2LaneFetch, manifest as r2_manifest } from '../r2/src/index.ts';

export function createCloudflareFetch(options: PackFetchOptions = {}): DerivedFetch {
  return createVendorFetch(manifest, { "api": { fetch: createApiLaneFetch(options), manifest: api_manifest }, "r2": { fetch: createR2LaneFetch(options), manifest: r2_manifest } });
}
